# Do not edit this file directly. It has been autogenerated from
# src/vulners/_transport_client_async.py
"""Async I/O client (unasyncd source for the sync :class:`SyncAPIClient`).

The sans-IO :class:`~vulners._base_client.BaseClient` holds every pure helper;
this module adds the small amount of real I/O — rate-limit pacing, the send,
capped reads, the retry loop and streaming — as :class:`SyncAPIClient`. The sync
mirror ``_transport_client_sync.py`` (:class:`SyncAPIClient`) is generated from
this file by ``unasyncd``, so the security-relevant retry/backoff/pacing logic
stays identical across the two transports by construction. Edit this file only.
"""

from __future__ import annotations

import time
from collections.abc import Callable, Iterator, Mapping
from typing import Any

import httpx
from typing_extensions import Self

from vulners._ratelimit import RateLimitBucket
from vulners._response import StreamedAPIResponse
from vulners._transport import VulnersTransport

from ._base_client import BaseClient, RequestSpec, _mount_guard
from ._config import ClientConfig
from ._exceptions import (
    APIConnectionError,
    APIStatusError,
    APITimeoutError,
    ErrorInfo,
)
from ._logging import logger
from ._response import APIResponse
from ._retry import _retry_timeout, _should_retry
from ._streaming import is_zip_media, iter_zip_json_array, make_array_decoder
from ._types import NotGiven, Omit, not_given


class SyncAPIClient(BaseClient):
    """Asynchronous request loop over an ``httpx.Client``."""

    def __init__(
        self,
        config: ClientConfig,
        http_client: httpx.Client | None = None,
        buckets: dict[str, RateLimitBucket] | None = None,
    ) -> None:
        super().__init__(config)
        # Account-scoped pacing buckets. A clone (with_options) passes the parent's
        # dict so client-side rate-limit pacing is shared, not reset per variant.
        self._buckets: dict[str, RateLimitBucket] = {} if buckets is None else buckets
        if http_client is not None:
            self._client = http_client
            self._owns_client = False
            # Wrap the caller's transport(s) so the cross-origin X-Api-Key strip,
            # set-cookie drop and SSRF redirect guard run on a BYO client too.
            _mount_guard(http_client, VulnersTransport, config.base_url)
        else:
            # h2 is a core dependency, so http2=True always works; no guard needed.
            transport = VulnersTransport(
                httpx.HTTPTransport(retries=config.connect_retries, http2=config.http2),
                origin=config.base_url,
            )
            self._client = httpx.Client(
                base_url=config.base_url,
                transport=transport,
                timeout=config.timeout,
                limits=config.limits,
                follow_redirects=config.follow_redirects,
            )
            self._owns_client = True

    def _bucket_for(self, key: str) -> RateLimitBucket:
        bucket = self._buckets.get(key)
        if bucket is None:
            bucket = self._buckets.setdefault(key, RateLimitBucket())
        return bucket

    def _send(self, spec: RequestSpec, request: httpx.Request) -> tuple[httpx.Response, bytes]:
        if self._config.max_response_bytes is None:
            response = self._client.send(request)
            return response, response.content
        response = self._client.send(request, stream=True)
        try:
            self._reject_declared_length(
                response.headers.get("content-length"), response.status_code
            )
            buf = bytearray()
            for chunk in response.iter_bytes():
                buf += chunk
                self._guard_cap(len(buf), response.status_code)
        finally:
            response.close()
        return response, bytes(buf)

    def _send_with_retries(
        self, spec: RequestSpec, request: httpx.Request, retries: int
    ) -> tuple[httpx.Response, bytes, Any]:
        bucket = self._bucket_for(self._ratelimit_key(spec))
        attempt = 0
        while True:
            bucket.consume(self._config.max_rate_limit_wait)
            try:
                response, content = self._send(spec, request)
            except httpx.TimeoutException as exc:
                error: APIConnectionError = APITimeoutError(f"Request timed out: {exc}")
                if attempt < retries and self._retryable_exc(exc, spec):
                    attempt += 1
                    self._sleep(_retry_timeout(attempt))
                    continue
                raise error from exc
            except httpx.TransportError as exc:
                error = APIConnectionError(f"Connection error: {exc}")
                if attempt < retries and self._retryable_exc(exc, spec):
                    attempt += 1
                    self._sleep(_retry_timeout(attempt))
                    continue
                raise error from exc
            self._update_bucket_from_headers(bucket, response)
            try:
                parsed = self._process_response(spec, response, content)
            except APIStatusError as err:
                info = ErrorInfo(status_code=err.status_code, error_code=err.error_code)
                if attempt < retries and _should_retry(
                    info, response.headers, idempotent=self._idempotent(spec)
                ):
                    attempt += 1
                    logger.debug(
                        "retrying %s %s after status %s", spec.method, spec.path, err.status_code
                    )
                    self._sleep(_retry_timeout(attempt, response.headers))
                    continue
                raise
            return response, content, parsed

    def request(
        self,
        spec: RequestSpec,
        *,
        cast: Callable[[Any], Any] | None = None,
        params: Mapping[str, Any] | None = None,
        body: Any = None,
        files: Any = None,
        headers: Mapping[str, str | Omit] | None = None,
        timeout: float | httpx.Timeout | None | NotGiven = not_given,
        max_retries: int | None = None,
    ) -> Any:
        retries = self._config.max_retries if max_retries is None else max_retries
        request = self._build_request(
            spec, params=params, body=body, files=files, headers=headers, timeout=timeout
        )
        _, _, parsed = self._send_with_retries(spec, request, retries)
        return cast(parsed) if cast is not None else parsed

    def request_with_response(
        self,
        spec: RequestSpec,
        *,
        cast: Callable[[Any], Any] | None = None,
        params: Mapping[str, Any] | None = None,
        body: Any = None,
        files: Any = None,
        headers: Mapping[str, str | Omit] | None = None,
        timeout: float | httpx.Timeout | None | NotGiven = not_given,
        max_retries: int | None = None,
    ) -> APIResponse[Any]:
        retries = self._config.max_retries if max_retries is None else max_retries
        request = self._build_request(
            spec, params=params, body=body, files=files, headers=headers, timeout=timeout
        )
        response, content, parsed = self._send_with_retries(spec, request, retries)
        return APIResponse(response, content, parsed, cast)

    def stream_records(
        self,
        spec: RequestSpec,
        *,
        params: Mapping[str, Any] | None = None,
        body: Any = None,
        timeout: float | httpx.Timeout | None | NotGiven = not_given,
    ) -> Iterator[Any]:
        """Lazily yield the elements of a streamed bulk-archive JSON array."""
        request = self._build_request(spec, params=params, body=body, timeout=timeout)
        bucket = self._bucket_for(self._ratelimit_key(spec))
        bucket.consume(self._config.max_rate_limit_wait)
        response = self._client.send(request, stream=True)
        try:
            self._update_bucket_from_headers(bucket, response)
            if response.status_code >= 400:
                self._raise_stream_error(response, response.read())
            media = self._media_type(response)
            cap = self._config.max_response_bytes
            if is_zip_media(media):
                buf = bytearray()
                for chunk in response.iter_bytes():
                    buf += chunk
                    if cap is not None:
                        self._guard_cap(len(buf), response.status_code)
                for record in iter_zip_json_array(bytes(buf), cap):
                    yield record
            else:
                # The decoder inflates and parses the JSON array lazily and
                # enforces the cap on the decompressed byte count.
                decoder = make_array_decoder(media, cap)
                for chunk in response.iter_bytes():
                    for record in decoder.feed(chunk):
                        yield record
                # feed() drains each chunk fully (ijson emits every element at its
                # closing brace), so flush() is a no-op for the array decoders; the
                # call is the decoder-protocol contract, kept for a buffering decoder.
                for record in decoder.flush():  # pragma: no cover
                    yield record
        finally:
            response.close()

    def stream_response(
        self,
        spec: RequestSpec,
        *,
        cast: Callable[[Any], Any] | None = None,
        params: Mapping[str, Any] | None = None,
        body: Any = None,
        files: Any = None,
        timeout: float | httpx.Timeout | None | NotGiven = not_given,
    ) -> SyncStreamContext:
        """A context manager yielding a live :class:`vulners._response.StreamedAPIResponse`."""
        request = self._build_request(
            spec, params=params, body=body, files=files, timeout=timeout
        )
        return SyncStreamContext(self, spec, request, cast)

    @staticmethod
    def _sleep(seconds: float) -> None:

        time.sleep(seconds)

    def get(self, path: str, *, params: Mapping[str, Any] | None = None, **kw: Any) -> Any:
        return self.request(RequestSpec("GET", path, body_mode="query"), params=params, **kw)

    def post(self, path: str, *, body: Any = None, **kw: Any) -> Any:
        return self.request(RequestSpec("POST", path, body_mode="json"), body=body, **kw)

    def put(self, path: str, *, body: Any = None, **kw: Any) -> Any:
        return self.request(RequestSpec("PUT", path, body_mode="json"), body=body, **kw)

    def delete(self, path: str, *, params: Mapping[str, Any] | None = None, **kw: Any) -> Any:
        return self.request(RequestSpec("DELETE", path, body_mode="query"), params=params, **kw)

    # -- lifecycle ---------------------------------------------------------

    @property
    def is_closed(self) -> bool:
        return self._client.is_closed

    def close(self) -> None:
        if self._owns_client and not self._client.is_closed:
            self._client.close()

    def __enter__(self) -> Self:
        return self

    def __exit__(self, *exc: object) -> None:
        self.close()


class SyncStreamContext:
    """Async context manager that opens a stream and yields a live response."""

    def __init__(
        self,
        client: SyncAPIClient,
        spec: RequestSpec,
        request: httpx.Request,
        cast: Callable[[Any], Any] | None,
    ) -> None:
        self._client = client
        self._spec = spec
        self._request = request
        self._cast = cast
        self._response: httpx.Response | None = None

    def __enter__(self) -> StreamedAPIResponse[Any]:
        client = self._client
        bucket = client._bucket_for(client._ratelimit_key(self._spec))
        bucket.consume(client._config.max_rate_limit_wait)
        response = client._client.send(self._request, stream=True)
        self._response = response
        client._update_bucket_from_headers(bucket, response)
        if response.status_code >= 400:
            content = response.read()
            try:
                client._raise_stream_error(response, content)
            finally:
                response.close()
        return StreamedAPIResponse(response, client._stream_parser(self._spec, self._cast))

    def __exit__(self, *exc: object) -> None:
        if self._response is not None:
            self._response.close()


__all__ = []
