"""Input TypedDicts for the v4 ``subscriptions`` resource.

The subscription ``query`` and ``delivery`` payloads are discriminated unions:
the ``type`` key picks the shape. Each variant below mirrors the server schema;
``create``/``update`` also accept a plain ``Mapping`` as an escape hatch, so an
unknown/new server shape never blocks a call.
"""

from __future__ import annotations

from collections.abc import Sequence
from typing import Literal

from typing_extensions import Required, TypedDict

from .audit import AuditItem


class SubscriptionQueryLucene(TypedDict, total=False):
    """Subscribe to a Lucene query (``type: "query"``)."""

    type: Required[Literal["query"]]
    query: Required[str]


class SubscriptionQuerySoftware(TypedDict, total=False):
    """Subscribe to a CPE software list (``type: "software"``)."""

    type: Required[Literal["software"]]
    software: Required[Sequence[str | AuditItem]]


class SubscriptionQueryHostGeneric(TypedDict, total=False):
    """Subscribe to a host described by CPEs (``type: "host/generic"``)."""

    type: Required[Literal["host/generic"]]
    software: Required[Sequence[str | AuditItem]]
    application: str | AuditItem
    operating_system: str | AuditItem
    hardware: str | AuditItem


class SubscriptionQueryHostLinux(TypedDict, total=False):
    """Subscribe to a Linux host's package list (``type: "host/linux"``)."""

    type: Required[Literal["host/linux"]]
    os: Required[str]
    os_version: Required[str]
    packages: Required[Sequence[str]]


class SubscriptionQueryHostWindows(TypedDict, total=False):
    """Subscribe to a Windows host's KBs and software (``type: "host/windows"``)."""

    type: Required[Literal["host/windows"]]
    os: Required[str]
    os_version: Required[str]
    kb_list: Required[Sequence[str]]
    packages: Required[Sequence[str]]


class SubscriptionQueryAuditLinux(TypedDict, total=False):
    """Subscribe to a Linux package audit (``type: "audit/linux"``)."""

    type: Required[Literal["audit/linux"]]
    os_name: Required[str]
    os_version: Required[str]
    packages: Required[Sequence[str]]
    os_arch: str
    include_unofficial: bool
    include_candidates: bool
    include_any_version: bool
    cvelist_metrics: bool


SubscriptionQuery = (
    SubscriptionQueryLucene
    | SubscriptionQuerySoftware
    | SubscriptionQueryHostGeneric
    | SubscriptionQueryHostLinux
    | SubscriptionQueryHostWindows
    | SubscriptionQueryAuditLinux
)
"""What to subscribe to, discriminated by ``type``."""


class SubscriptionDeliveryWebhook(TypedDict, total=False):
    """Push results to a webhook on a schedule (``type: "webhook"``)."""

    type: Required[Literal["webhook"]]
    address: Required[str]
    crontab: Required[str]


class SubscriptionDeliveryPolling(TypedDict, total=False):
    """Poll results from a server-generated URL (``type: "pooling"``).

    Polling is spelled ``pooling`` on the wire — a historical spelling kept for
    compatibility. ``endpoint`` is generated by the server on create.
    """

    type: Required[Literal["pooling"]]
    endpoint: str | None


SubscriptionDelivery = SubscriptionDeliveryWebhook | SubscriptionDeliveryPolling
"""How results are delivered, discriminated by ``type``."""


__all__ = [
    "SubscriptionDelivery",
    "SubscriptionDeliveryPolling",
    "SubscriptionDeliveryWebhook",
    "SubscriptionQuery",
    "SubscriptionQueryAuditLinux",
    "SubscriptionQueryHostGeneric",
    "SubscriptionQueryHostLinux",
    "SubscriptionQueryHostWindows",
    "SubscriptionQueryLucene",
    "SubscriptionQuerySoftware",
]
