"""GENERATED bulletin models — do not edit.

The base -> family -> type hierarchy, one file per bulletinFamily. Every class
is imported here explicitly (so static analysis and IDEs see the whole surface),
and mapped in FAMILY_MODELS / TYPE_MODELS for runtime type -> class resolution.
Regenerate from live data with::

    python dev-tools/data-models/sample_collections.py
"""

from __future__ import annotations

from .base import Bulletin, GenericBulletin
from .blogBulletins import (
    AkamaiblogBulletin,
    AnandprakaBulletin,
    AvleonovBulletin,
    BlogBulletin,
    CarbonblackBulletin,
    CoalfireBulletin,
    D0znppBulletin,
    FilippoioBulletin,
    HackreadBulletin,
    ImpervablogBulletin,
    IntothesymmetryBulletin,
    JakearchibaldBulletin,
    KrebsBulletin,
    MalwarebytesBulletin,
    MmpcBulletin,
    MsrcBulletin,
    MssecureBulletin,
    PentestitBulletin,
    PentestlabBulletin,
    PentestnepalBulletin,
    PentestpartnersBulletin,
    QualysblogBulletin,
    Rapid7communityBulletin,
    RhinoBulletin,
    RipstechBulletin,
    SchneierBulletin,
    SecurelistBulletin,
    SilentrobotsBulletin,
    SonarsourceBulletin,
    TalosblogBulletin,
    TaosecurityBulletin,
    ThehackerblogBulletin,
    TrendmicroblogBulletin,
    WallarmlabBulletin,
    WebsecuritylogBulletin,
    WiredBulletin,
)
from .bugbountyBulletins import (
    BugbountyBulletin,
    HackeroneBulletin,
    HuntrBulletin,
    OpenbugbountyBulletin,
    XssedBulletin,
)
from .cnnvdBulletins import (
    CnnvdBulletin,
    CnnvdCollectionBulletin,
)
from .cnvdBulletins import (
    CnvdBulletin,
    CnvdCollectionBulletin,
)
from .cryptoBulletins import (
    Code423n4Bulletin,
    CryptoBulletin,
)
from .cveBulletins import (
    CveBulletin,
    CveCollectionBulletin,
    CvelistBulletin,
    NvdBulletin,
    PrionBulletin,
    VulnrichmentBulletin,
)
from .euvdBulletins import (
    EuvdBulletin,
    EuvdCollectionBulletin,
)
from .exploitBulletins import (
    C0daydbBulletin,
    CanvasBulletin,
    D2Bulletin,
    DsquareBulletin,
    ExploitBulletin,
    ExploitdbBulletin,
    ExploitpackBulletin,
    GiteeBulletin,
    GithubexploitBulletin,
    MetasploitBulletin,
    PacketstormBulletin,
    PwnmalwBulletin,
    SaintBulletin,
    SeebugBulletin,
    SrcinciteBulletin,
    VulnerlabBulletin,
    WpexploitBulletin,
    ZdtBulletin,
    ZeroscienceBulletin,
)
from .infoBulletins import (
    AmdBulletin,
    AttackerkbBulletin,
    BduFstecBulletin,
    BinamuseBulletin,
    CertBulletin,
    CheckpointAdvisoriesBulletin,
    CirclBulletin,
    CisaBulletin,
    CisaKevBulletin,
    CiscothreatsBulletin,
    CoresecurityBulletin,
    Cve0dayBulletin,
    DuoBulletin,
    ErpscanBulletin,
    FireeyeBulletin,
    GoogleprojectzeroBulletin,
    HiveproBulletin,
    IcsBulletin,
    InfoBulletin,
    IntelBulletin,
    KasperskyBulletin,
    LenovoBulletin,
    Myhack58Bulletin,
    PacketstormnewsBulletin,
    PtsecurityBulletin,
    QtBulletin,
    Rapid7blogBulletin,
    RdotBulletin,
    RedhatcveBulletin,
    SambaBulletin,
    SecurityVulnsBulletin,
    SpringBulletin,
    TalosBulletin,
    TenableBulletin,
    ThnBulletin,
    ThreatpostBulletin,
    TrellixBulletin,
    VulncheckKevBulletin,
    WizblogBulletin,
    WordfenceBulletin,
    ZdiBulletin,
)
from .jvnBulletins import (
    JvnBulletin,
    JvnCollectionBulletin,
)
from .libraryBulletins import (
    LibraryBulletin,
    OsvBulletin,
    SnykBulletin,
    VulnersosvBulletin,
)
from .microsoftBulletins import (
    MicrosoftBulletin,
    MscveBulletin,
    MskbBulletin,
    MsupdateBulletin,
)
from .ncscBulletins import (
    NcscBulletin,
    NcscCollectionBulletin,
)
from .nozomiBulletins import (
    NozomiBulletin,
    NozomiCollectionBulletin,
)
from .scannerBulletins import (
    NessusBulletin,
    NmapBulletin,
    NucleiBulletin,
    OpenvasBulletin,
    ScannerBulletin,
    W3afBulletin,
)
from .softwareBulletins import (
    AdobeBulletin,
    AndroidBulletin,
    AndroidsecurityBulletin,
    AnthropicBulletin,
    AppercutBulletin,
    AppleBulletin,
    AristaBulletin,
    AtlassianBulletin,
    BraveBulletin,
    BroadcomBulletin,
    CakephpBulletin,
    CheckpointSecurityBulletin,
    ChromeBulletin,
    CiscoBulletin,
    CitrixBulletin,
    ClickhouseBulletin,
    CloudfoundryBulletin,
    ContaoBulletin,
    CurlBulletin,
    DrupalBulletin,
    ElasticBulletin,
    F5Bulletin,
    FortinetBulletin,
    FriendsofphpBulletin,
    FuelphpBulletin,
    GithubBulletin,
    GitlabBulletin,
    GrafanaBulletin,
    HackappBulletin,
    HashicorpBulletin,
    HpBulletin,
    HpeBulletin,
    HtbridgeBulletin,
    HttpdBulletin,
    HuaweiBulletin,
    IbmBulletin,
    IvantiBulletin,
    JenkinsBulletin,
    JetbrainsBulletin,
    JoomlaBulletin,
    KorelogicBulletin,
    KubernetesBulletin,
    LaminasBulletin,
    ModxBulletin,
    MongodbBulletin,
    MozillaBulletin,
    MsvrBulletin,
    NextcloudBulletin,
    NginxBulletin,
    NodejsblogBulletin,
    NodejsBulletin,
    NvidiaBulletin,
    OpensslBulletin,
    OperaBulletin,
    OracleBulletin,
    OssfBulletin,
    OssfuzzBulletin,
    OwncloudBulletin,
    PaloaltoBulletin,
    PatchstackBulletin,
    PhpmyadminBulletin,
    PostgresqlBulletin,
    PypaBulletin,
    RubygemsBulletin,
    RustsecBulletin,
    SecurityvulnsBulletin,
    SickBulletin,
    SoftwareBulletin,
    SonicwallBulletin,
    SqliteBulletin,
    SymantecBulletin,
    SymfonyBulletin,
    TibcoBulletin,
    TomcatBulletin,
    Typo3Bulletin,
    VaadinBulletin,
    VeeamBulletin,
    VeracodeBulletin,
    VivaldiBulletin,
    VmwareBulletin,
    WpvulndbBulletin,
    XenBulletin,
    YubicoBulletin,
)
from .toolsBulletins import (
    KitploitBulletin,
    N0whereBulletin,
    ToolsBulletin,
)
from .unixBulletins import (
    AixBulletin,
    AlmalinuxBulletin,
    AlpinelinuxBulletin,
    AltlinuxBulletin,
    AmazonBulletin,
    ArchlinuxBulletin,
    AstralinuxBulletin,
    CblMarinerBulletin,
    CentosBulletin,
    CgrBulletin,
    CloudlinuxBulletin,
    DebianBulletin,
    DebiancveBulletin,
    FedoraBulletin,
    FreebsdAdvisoryBulletin,
    FreebsdBulletin,
    GentooBulletin,
    MageiaBulletin,
    MariadbunixBulletin,
    OpensuseBulletin,
    OpenwrtBulletin,
    OraclelinuxBulletin,
    PhotonBulletin,
    RedhatBulletin,
    RedosBulletin,
    RockyBulletin,
    RosalinuxBulletin,
    SlackwareBulletin,
    SuseBulletin,
    SusecveBulletin,
    UbuntuBulletin,
    UbuntucveBulletin,
    UnixBulletin,
    VirtuozzoBulletin,
    WolfiBulletin,
)

FAMILY_MODELS: dict[str, type[Bulletin]] = {
    "blog": BlogBulletin,
    "bugbounty": BugbountyBulletin,
    "cnnvd": CnnvdBulletin,
    "cnvd": CnvdBulletin,
    "crypto": CryptoBulletin,
    "cve": CveBulletin,
    "euvd": EuvdBulletin,
    "exploit": ExploitBulletin,
    "info": InfoBulletin,
    "jvn": JvnBulletin,
    "library": LibraryBulletin,
    "microsoft": MicrosoftBulletin,
    "ncsc": NcscBulletin,
    "nozomi": NozomiBulletin,
    "scanner": ScannerBulletin,
    "software": SoftwareBulletin,
    "tools": ToolsBulletin,
    "unix": UnixBulletin,
}

TYPE_MODELS: dict[str, type[Bulletin]] = {
    "0daydb": C0daydbBulletin,
    "adobe": AdobeBulletin,
    "aix": AixBulletin,
    "akamaiblog": AkamaiblogBulletin,
    "almalinux": AlmalinuxBulletin,
    "alpinelinux": AlpinelinuxBulletin,
    "altlinux": AltlinuxBulletin,
    "amazon": AmazonBulletin,
    "amd": AmdBulletin,
    "anandpraka": AnandprakaBulletin,
    "android": AndroidBulletin,
    "androidsecurity": AndroidsecurityBulletin,
    "anthropic": AnthropicBulletin,
    "appercut": AppercutBulletin,
    "apple": AppleBulletin,
    "archlinux": ArchlinuxBulletin,
    "arista": AristaBulletin,
    "astralinux": AstralinuxBulletin,
    "atlassian": AtlassianBulletin,
    "attackerkb": AttackerkbBulletin,
    "avleonov": AvleonovBulletin,
    "bdu_fstec": BduFstecBulletin,
    "binamuse": BinamuseBulletin,
    "brave": BraveBulletin,
    "broadcom": BroadcomBulletin,
    "cakephp": CakephpBulletin,
    "canvas": CanvasBulletin,
    "carbonblack": CarbonblackBulletin,
    "cbl_mariner": CblMarinerBulletin,
    "centos": CentosBulletin,
    "cert": CertBulletin,
    "cgr": CgrBulletin,
    "checkpoint_advisories": CheckpointAdvisoriesBulletin,
    "checkpoint_security": CheckpointSecurityBulletin,
    "chrome": ChromeBulletin,
    "circl": CirclBulletin,
    "cisa": CisaBulletin,
    "cisa_kev": CisaKevBulletin,
    "cisco": CiscoBulletin,
    "ciscothreats": CiscothreatsBulletin,
    "citrix": CitrixBulletin,
    "clickhouse": ClickhouseBulletin,
    "cloudfoundry": CloudfoundryBulletin,
    "cloudlinux": CloudlinuxBulletin,
    "cnnvd": CnnvdCollectionBulletin,
    "cnvd": CnvdCollectionBulletin,
    "coalfire": CoalfireBulletin,
    "code423n4": Code423n4Bulletin,
    "contao": ContaoBulletin,
    "coresecurity": CoresecurityBulletin,
    "curl": CurlBulletin,
    "cve": CveCollectionBulletin,
    "cve0day": Cve0dayBulletin,
    "cvelist": CvelistBulletin,
    "d0znpp": D0znppBulletin,
    "d2": D2Bulletin,
    "debian": DebianBulletin,
    "debiancve": DebiancveBulletin,
    "drupal": DrupalBulletin,
    "dsquare": DsquareBulletin,
    "duo": DuoBulletin,
    "elastic": ElasticBulletin,
    "erpscan": ErpscanBulletin,
    "euvd": EuvdCollectionBulletin,
    "exploitdb": ExploitdbBulletin,
    "exploitpack": ExploitpackBulletin,
    "f5": F5Bulletin,
    "fedora": FedoraBulletin,
    "filippoio": FilippoioBulletin,
    "fireeye": FireeyeBulletin,
    "fortinet": FortinetBulletin,
    "freebsd": FreebsdBulletin,
    "freebsd_advisory": FreebsdAdvisoryBulletin,
    "friendsofphp": FriendsofphpBulletin,
    "fuelphp": FuelphpBulletin,
    "gentoo": GentooBulletin,
    "gitee": GiteeBulletin,
    "github": GithubBulletin,
    "githubexploit": GithubexploitBulletin,
    "gitlab": GitlabBulletin,
    "googleprojectzero": GoogleprojectzeroBulletin,
    "grafana": GrafanaBulletin,
    "hackapp": HackappBulletin,
    "hackerone": HackeroneBulletin,
    "hackread": HackreadBulletin,
    "hashicorp": HashicorpBulletin,
    "hivepro": HiveproBulletin,
    "hp": HpBulletin,
    "hpe": HpeBulletin,
    "htbridge": HtbridgeBulletin,
    "httpd": HttpdBulletin,
    "huawei": HuaweiBulletin,
    "huntr": HuntrBulletin,
    "ibm": IbmBulletin,
    "ics": IcsBulletin,
    "impervablog": ImpervablogBulletin,
    "intel": IntelBulletin,
    "intothesymmetry": IntothesymmetryBulletin,
    "ivanti": IvantiBulletin,
    "jakearchibald": JakearchibaldBulletin,
    "jenkins": JenkinsBulletin,
    "jetbrains": JetbrainsBulletin,
    "joomla": JoomlaBulletin,
    "jvn": JvnCollectionBulletin,
    "kaspersky": KasperskyBulletin,
    "kitploit": KitploitBulletin,
    "korelogic": KorelogicBulletin,
    "krebs": KrebsBulletin,
    "kubernetes": KubernetesBulletin,
    "laminas": LaminasBulletin,
    "lenovo": LenovoBulletin,
    "mageia": MageiaBulletin,
    "malwarebytes": MalwarebytesBulletin,
    "mariadbunix": MariadbunixBulletin,
    "metasploit": MetasploitBulletin,
    "mmpc": MmpcBulletin,
    "modx": ModxBulletin,
    "mongodb": MongodbBulletin,
    "mozilla": MozillaBulletin,
    "mscve": MscveBulletin,
    "mskb": MskbBulletin,
    "msrc": MsrcBulletin,
    "mssecure": MssecureBulletin,
    "msupdate": MsupdateBulletin,
    "msvr": MsvrBulletin,
    "myhack58": Myhack58Bulletin,
    "n0where": N0whereBulletin,
    "ncsc": NcscCollectionBulletin,
    "nessus": NessusBulletin,
    "nextcloud": NextcloudBulletin,
    "nginx": NginxBulletin,
    "nmap": NmapBulletin,
    "nodejs": NodejsBulletin,
    "nodejsblog": NodejsblogBulletin,
    "nozomi": NozomiCollectionBulletin,
    "nuclei": NucleiBulletin,
    "nvd": NvdBulletin,
    "nvidia": NvidiaBulletin,
    "openbugbounty": OpenbugbountyBulletin,
    "openssl": OpensslBulletin,
    "opensuse": OpensuseBulletin,
    "openvas": OpenvasBulletin,
    "openwrt": OpenwrtBulletin,
    "opera": OperaBulletin,
    "oracle": OracleBulletin,
    "oraclelinux": OraclelinuxBulletin,
    "ossf": OssfBulletin,
    "ossfuzz": OssfuzzBulletin,
    "osv": OsvBulletin,
    "owncloud": OwncloudBulletin,
    "packetstorm": PacketstormBulletin,
    "packetstormnews": PacketstormnewsBulletin,
    "paloalto": PaloaltoBulletin,
    "patchstack": PatchstackBulletin,
    "pentestit": PentestitBulletin,
    "pentestlab": PentestlabBulletin,
    "pentestnepal": PentestnepalBulletin,
    "pentestpartners": PentestpartnersBulletin,
    "photon": PhotonBulletin,
    "phpmyadmin": PhpmyadminBulletin,
    "postgresql": PostgresqlBulletin,
    "prion": PrionBulletin,
    "ptsecurity": PtsecurityBulletin,
    "pwnmalw": PwnmalwBulletin,
    "pypa": PypaBulletin,
    "qt": QtBulletin,
    "qualysblog": QualysblogBulletin,
    "rapid7blog": Rapid7blogBulletin,
    "rapid7community": Rapid7communityBulletin,
    "rdot": RdotBulletin,
    "redhat": RedhatBulletin,
    "redhatcve": RedhatcveBulletin,
    "redos": RedosBulletin,
    "rhino": RhinoBulletin,
    "ripstech": RipstechBulletin,
    "rocky": RockyBulletin,
    "rosalinux": RosalinuxBulletin,
    "rubygems": RubygemsBulletin,
    "rustsec": RustsecBulletin,
    "saint": SaintBulletin,
    "samba": SambaBulletin,
    "schneier": SchneierBulletin,
    "securelist": SecurelistBulletin,
    "security_vulns": SecurityVulnsBulletin,
    "securityvulns": SecurityvulnsBulletin,
    "seebug": SeebugBulletin,
    "sick": SickBulletin,
    "silentrobots": SilentrobotsBulletin,
    "slackware": SlackwareBulletin,
    "snyk": SnykBulletin,
    "sonarsource": SonarsourceBulletin,
    "sonicwall": SonicwallBulletin,
    "spring": SpringBulletin,
    "sqlite": SqliteBulletin,
    "srcincite": SrcinciteBulletin,
    "suse": SuseBulletin,
    "susecve": SusecveBulletin,
    "symantec": SymantecBulletin,
    "symfony": SymfonyBulletin,
    "talos": TalosBulletin,
    "talosblog": TalosblogBulletin,
    "taosecurity": TaosecurityBulletin,
    "tenable": TenableBulletin,
    "thehackerblog": ThehackerblogBulletin,
    "thn": ThnBulletin,
    "threatpost": ThreatpostBulletin,
    "tibco": TibcoBulletin,
    "tomcat": TomcatBulletin,
    "trellix": TrellixBulletin,
    "trendmicroblog": TrendmicroblogBulletin,
    "typo3": Typo3Bulletin,
    "ubuntu": UbuntuBulletin,
    "ubuntucve": UbuntucveBulletin,
    "vaadin": VaadinBulletin,
    "veeam": VeeamBulletin,
    "veracode": VeracodeBulletin,
    "virtuozzo": VirtuozzoBulletin,
    "vivaldi": VivaldiBulletin,
    "vmware": VmwareBulletin,
    "vulncheck_kev": VulncheckKevBulletin,
    "vulnerlab": VulnerlabBulletin,
    "vulnersosv": VulnersosvBulletin,
    "vulnrichment": VulnrichmentBulletin,
    "w3af": W3afBulletin,
    "wallarmlab": WallarmlabBulletin,
    "websecuritylog": WebsecuritylogBulletin,
    "wired": WiredBulletin,
    "wizblog": WizblogBulletin,
    "wolfi": WolfiBulletin,
    "wordfence": WordfenceBulletin,
    "wpexploit": WpexploitBulletin,
    "wpvulndb": WpvulndbBulletin,
    "xen": XenBulletin,
    "xssed": XssedBulletin,
    "yubico": YubicoBulletin,
    "zdi": ZdiBulletin,
    "zdt": ZdtBulletin,
    "zeroscience": ZeroscienceBulletin,
}

__all__ = [
    "AdobeBulletin",
    "AixBulletin",
    "AkamaiblogBulletin",
    "AlmalinuxBulletin",
    "AlpinelinuxBulletin",
    "AltlinuxBulletin",
    "AmazonBulletin",
    "AmdBulletin",
    "AnandprakaBulletin",
    "AndroidBulletin",
    "AndroidsecurityBulletin",
    "AnthropicBulletin",
    "AppercutBulletin",
    "AppleBulletin",
    "ArchlinuxBulletin",
    "AristaBulletin",
    "AstralinuxBulletin",
    "AtlassianBulletin",
    "AttackerkbBulletin",
    "AvleonovBulletin",
    "BduFstecBulletin",
    "BinamuseBulletin",
    "BlogBulletin",
    "BraveBulletin",
    "BroadcomBulletin",
    "BugbountyBulletin",
    "Bulletin",
    "C0daydbBulletin",
    "CakephpBulletin",
    "CanvasBulletin",
    "CarbonblackBulletin",
    "CblMarinerBulletin",
    "CentosBulletin",
    "CertBulletin",
    "CgrBulletin",
    "CheckpointAdvisoriesBulletin",
    "CheckpointSecurityBulletin",
    "ChromeBulletin",
    "CirclBulletin",
    "CisaBulletin",
    "CisaKevBulletin",
    "CiscoBulletin",
    "CiscothreatsBulletin",
    "CitrixBulletin",
    "ClickhouseBulletin",
    "CloudfoundryBulletin",
    "CloudlinuxBulletin",
    "CnnvdBulletin",
    "CnnvdCollectionBulletin",
    "CnvdBulletin",
    "CnvdCollectionBulletin",
    "CoalfireBulletin",
    "Code423n4Bulletin",
    "ContaoBulletin",
    "CoresecurityBulletin",
    "CryptoBulletin",
    "CurlBulletin",
    "Cve0dayBulletin",
    "CveBulletin",
    "CveCollectionBulletin",
    "CvelistBulletin",
    "D0znppBulletin",
    "D2Bulletin",
    "DebianBulletin",
    "DebiancveBulletin",
    "DrupalBulletin",
    "DsquareBulletin",
    "DuoBulletin",
    "ElasticBulletin",
    "ErpscanBulletin",
    "EuvdBulletin",
    "EuvdCollectionBulletin",
    "ExploitBulletin",
    "ExploitdbBulletin",
    "ExploitpackBulletin",
    "F5Bulletin",
    "FedoraBulletin",
    "FilippoioBulletin",
    "FireeyeBulletin",
    "FortinetBulletin",
    "FreebsdAdvisoryBulletin",
    "FreebsdBulletin",
    "FriendsofphpBulletin",
    "FuelphpBulletin",
    "GenericBulletin",
    "GentooBulletin",
    "GiteeBulletin",
    "GithubBulletin",
    "GithubexploitBulletin",
    "GitlabBulletin",
    "GoogleprojectzeroBulletin",
    "GrafanaBulletin",
    "HackappBulletin",
    "HackeroneBulletin",
    "HackreadBulletin",
    "HashicorpBulletin",
    "HiveproBulletin",
    "HpBulletin",
    "HpeBulletin",
    "HtbridgeBulletin",
    "HttpdBulletin",
    "HuaweiBulletin",
    "HuntrBulletin",
    "IbmBulletin",
    "IcsBulletin",
    "ImpervablogBulletin",
    "InfoBulletin",
    "IntelBulletin",
    "IntothesymmetryBulletin",
    "IvantiBulletin",
    "JakearchibaldBulletin",
    "JenkinsBulletin",
    "JetbrainsBulletin",
    "JoomlaBulletin",
    "JvnBulletin",
    "JvnCollectionBulletin",
    "KasperskyBulletin",
    "KitploitBulletin",
    "KorelogicBulletin",
    "KrebsBulletin",
    "KubernetesBulletin",
    "LaminasBulletin",
    "LenovoBulletin",
    "LibraryBulletin",
    "MageiaBulletin",
    "MalwarebytesBulletin",
    "MariadbunixBulletin",
    "MetasploitBulletin",
    "MicrosoftBulletin",
    "MmpcBulletin",
    "ModxBulletin",
    "MongodbBulletin",
    "MozillaBulletin",
    "MscveBulletin",
    "MskbBulletin",
    "MsrcBulletin",
    "MssecureBulletin",
    "MsupdateBulletin",
    "MsvrBulletin",
    "Myhack58Bulletin",
    "N0whereBulletin",
    "NcscBulletin",
    "NcscCollectionBulletin",
    "NessusBulletin",
    "NextcloudBulletin",
    "NginxBulletin",
    "NmapBulletin",
    "NodejsBulletin",
    "NodejsblogBulletin",
    "NozomiBulletin",
    "NozomiCollectionBulletin",
    "NucleiBulletin",
    "NvdBulletin",
    "NvidiaBulletin",
    "OpenbugbountyBulletin",
    "OpensslBulletin",
    "OpensuseBulletin",
    "OpenvasBulletin",
    "OpenwrtBulletin",
    "OperaBulletin",
    "OracleBulletin",
    "OraclelinuxBulletin",
    "OssfBulletin",
    "OssfuzzBulletin",
    "OsvBulletin",
    "OwncloudBulletin",
    "PacketstormBulletin",
    "PacketstormnewsBulletin",
    "PaloaltoBulletin",
    "PatchstackBulletin",
    "PentestitBulletin",
    "PentestlabBulletin",
    "PentestnepalBulletin",
    "PentestpartnersBulletin",
    "PhotonBulletin",
    "PhpmyadminBulletin",
    "PostgresqlBulletin",
    "PrionBulletin",
    "PtsecurityBulletin",
    "PwnmalwBulletin",
    "PypaBulletin",
    "QtBulletin",
    "QualysblogBulletin",
    "Rapid7blogBulletin",
    "Rapid7communityBulletin",
    "RdotBulletin",
    "RedhatBulletin",
    "RedhatcveBulletin",
    "RedosBulletin",
    "RhinoBulletin",
    "RipstechBulletin",
    "RockyBulletin",
    "RosalinuxBulletin",
    "RubygemsBulletin",
    "RustsecBulletin",
    "SaintBulletin",
    "SambaBulletin",
    "ScannerBulletin",
    "SchneierBulletin",
    "SecurelistBulletin",
    "SecurityVulnsBulletin",
    "SecurityvulnsBulletin",
    "SeebugBulletin",
    "SickBulletin",
    "SilentrobotsBulletin",
    "SlackwareBulletin",
    "SnykBulletin",
    "SoftwareBulletin",
    "SonarsourceBulletin",
    "SonicwallBulletin",
    "SpringBulletin",
    "SqliteBulletin",
    "SrcinciteBulletin",
    "SuseBulletin",
    "SusecveBulletin",
    "SymantecBulletin",
    "SymfonyBulletin",
    "TalosBulletin",
    "TalosblogBulletin",
    "TaosecurityBulletin",
    "TenableBulletin",
    "ThehackerblogBulletin",
    "ThnBulletin",
    "ThreatpostBulletin",
    "TibcoBulletin",
    "TomcatBulletin",
    "ToolsBulletin",
    "TrellixBulletin",
    "TrendmicroblogBulletin",
    "Typo3Bulletin",
    "UbuntuBulletin",
    "UbuntucveBulletin",
    "UnixBulletin",
    "VaadinBulletin",
    "VeeamBulletin",
    "VeracodeBulletin",
    "VirtuozzoBulletin",
    "VivaldiBulletin",
    "VmwareBulletin",
    "VulncheckKevBulletin",
    "VulnerlabBulletin",
    "VulnersosvBulletin",
    "VulnrichmentBulletin",
    "W3afBulletin",
    "WallarmlabBulletin",
    "WebsecuritylogBulletin",
    "WiredBulletin",
    "WizblogBulletin",
    "WolfiBulletin",
    "WordfenceBulletin",
    "WpexploitBulletin",
    "WpvulndbBulletin",
    "XenBulletin",
    "XssedBulletin",
    "YubicoBulletin",
    "ZdiBulletin",
    "ZdtBulletin",
    "ZeroscienceBulletin",
]
