"""Offline coherence check of the generated model data (no API key).

``src/vulners/_models/_collections_data.py`` (generated by --emit-models) is the
committed baseline of what Vulners serves; this confirms it stays coherent with the
hand-written models and the authored descriptions. Also run by the test suite.
"""

from __future__ import annotations

from typing import Any


def _fields_missing_description(bmod: Any, type_models: dict) -> list[str]:
    """Declared model fields (family + generated type models, incl. inherited)
    whose ``description`` is empty — a field that lacks an authored docstring."""
    models = set(bmod._FAMILY_MODELS.values()) | {bmod.Bulletin} | set(type_models.values())
    missing = {
        f"{m.__name__}.{name}"
        for m in models
        for name, fi in m.model_fields.items()
        if not (fi.description or "").strip()
    }
    return sorted(missing)


def verify() -> int:
    """Fail (exit 1) if any collection family is unmapped, any collection field is
    undescribed, or any model field lacks a description. Run after --emit-models."""
    from vulners._models import bulletin as bmod
    from vulners._models._field_descriptions import FIELD_DESCRIPTIONS
    from vulners._models.collections import COLLECTIONS, collection_model

    families = {s["family"] for s in COLLECTIONS.values() if s.get("family")}
    fields = {w for s in COLLECTIONS.values() for w in s.get("fields", {})}

    def _trunc(items: list[str]) -> str:
        return f"{items[:10]}{'…' if len(items) > 10 else ''}"

    problems: list[str] = []
    unmapped_fam = sorted(families - set(bmod._FAMILY_MODELS))
    if unmapped_fam:
        problems.append(f"bulletinFamily not in _FAMILY_MODELS: {unmapped_fam}")
    undescribed = sorted(fields - set(FIELD_DESCRIPTIONS))
    if undescribed:
        problems.append(
            f"{len(undescribed)} field(s) with no description in _field_descriptions.py "
            f"(author one): {undescribed}"
        )
    # Build EVERY collection model (offline) and confirm no field lacks a
    # description — this exercises the whole base -> family -> type factory.
    built = [collection_model(t) for t in COLLECTIONS]
    missing_doc = _fields_missing_description(bmod, {m.__name__: m for m in built if m})
    if missing_doc:
        problems.append(
            f"{len(missing_doc)} model field(s) without a description: {_trunc(missing_doc)}"
        )

    if problems:
        print("DRIFT — the data model is out of sync:")
        for p in problems:
            print("  -", p)
        return 1
    print(
        f"OK: {len(COLLECTIONS)} collections, {len(families)} families, {len(fields)} "
        "type-specific fields — all mapped to models and described."
    )
    return 0
