# Do not edit this file directly. It has been autogenerated from
# src/vulners/_resources/_async/_base.py
"""Base class for async resources (unasyncd source for the sync resources).

Resources are stateless thin wrappers over the client's request loop. A resource
obtained via :attr:`with_raw_response` / :attr:`with_streaming_response` is a
sibling instance flagged so its methods return an :class:`APIResponse` instead of
the parsed model.
"""

from __future__ import annotations

from collections.abc import Callable, Mapping
from typing import TYPE_CHECKING, Any, TypeVar, overload

from typing_extensions import Self

from vulners._transport_client_sync import SyncAPIClient

from ..._base_client import RequestSpec
from ..._types import NotGiven, not_given

if TYPE_CHECKING:
    import httpx


_T = TypeVar("_T")


class BaseResource:
    """Common wiring shared by every async resource."""

    def __init__(self, client: SyncAPIClient, _wrap: str | None = None) -> None:
        self._client = client
        self._wrap = _wrap

    @property
    def _api_key(self) -> str:
        """The configured API key value, for endpoints that echo it in query/body."""
        return self._client.config.api_key.get_secret_value()

    @overload
    def _set(self, body: dict[str, Any], key: str, value: object) -> None: ...
    @overload
    def _set(
        self,
        body: dict[str, Any],
        key: str,
        value: _T | NotGiven,
        transform: Callable[[_T], object],
    ) -> None: ...
    def _set(
        self,
        body: dict[str, Any],
        key: str,
        value: Any,
        transform: Callable[[Any], Any] | None = None,
    ) -> None:
        """Add ``key`` to ``body`` unless ``value`` was not given.

        Consolidates the ``if not isinstance(value, NotGiven): body[key] = ...``
        idiom repeated across the resources; ``transform`` (e.g. ``list``) is
        applied to the value when present.
        """
        if not isinstance(value, NotGiven):
            body[key] = transform(value) if transform is not None else value

    @property
    def with_raw_response(self) -> Self:
        """A view whose methods return an :class:`~vulners._response.APIResponse`.

        Call the same method as on the resource, then read ``.status_code`` /
        ``.headers`` / ``.content`` and ``.parse()`` for the typed value. (The
        method annotations still show the parsed return type — the wrapper types
        are not yet declared; the runtime object is an ``APIResponse``.)
        """
        return type(self)(self._client, _wrap="raw")

    @property
    def with_streaming_response(self) -> Self:
        """A view whose methods return a streaming-response context manager.

        Each method returns a context manager; enter it (``with ... as response``
        / ``with ... as response``) to get a live
        :class:`~vulners._response.StreamedAPIResponse` and iterate the body off
        the wire with ``iter_bytes`` / ``iter_lines`` / ``iter_text`` (async:
        ``iter_*``) or read it and ``parse()``.
        """
        return type(self)(self._client, _wrap="stream")

    def _request(
        self,
        spec: RequestSpec,
        *,
        cast: Callable[[Any], Any] | None = None,
        params: Mapping[str, Any] | None = None,
        body: Any = None,
        files: Any = None,
        timeout: float | httpx.Timeout | None | NotGiven = not_given,
    ) -> Any:
        if self._wrap == "raw":
            return self._client.request_with_response(
                spec, cast=cast, params=params, body=body, files=files, timeout=timeout
            )
        if self._wrap == "stream":
            # Returns a (async) context manager; the caller drives it with
            # ``(async) with ... as response`` for live iteration / parse.
            return self._client.stream_response(
                spec, cast=cast, params=params, body=body, files=files, timeout=timeout
            )
        return self._client.request(
            spec, cast=cast, params=params, body=body, files=files, timeout=timeout
        )
