# Do not edit this file directly. It has been autogenerated from
# src/vulners/_resources/_async/archive.py
"""Async ``archive`` resource (unasyncd source for the sync ``archive`` resource).

Bulk collection / distributive / getsploit downloads. These endpoints return
whole compressed archives; the ``fetch_*``/``get_*`` methods match the v3
behaviour of buffering and decoding the whole body, while :meth:`iter_collection`
streams the elements of the (gzip/zip-compressed) JSON array lazily. Large
collections can be gigabytes, so they use the archive timeout profile.
"""

from __future__ import annotations

from collections.abc import Iterator
from datetime import datetime
from typing import Any

import httpx
import orjson

from ..._base_client import RequestSpec
from ..._types import NotGiven, not_given
from . import _base

_FETCH_COLLECTION = RequestSpec(
    "GET",
    "/api/v4/archive/collection",
    body_mode="query",
    response_mode="bytes",
    timeout_profile="archive",
)
_STREAM_COLLECTION = RequestSpec(
    "GET",
    "/api/v4/archive/collection",
    body_mode="query",
    response_mode="stream",
    timeout_profile="archive",
)
_FETCH_COLLECTION_UPDATE = RequestSpec(
    "GET",
    "/api/v4/archive/collection-update",
    body_mode="query",
    response_mode="bytes",
    timeout_profile="archive",
)
_GET_COLLECTION = RequestSpec(
    "GET",
    "/api/v3/archive/collection/",
    body_mode="query",
    response_mode="bytes",
    timeout_profile="archive",
)
_GET_DISTRIBUTIVE = RequestSpec(
    "GET",
    "/api/v3/archive/distributive/",
    body_mode="query",
    response_mode="bytes",
    timeout_profile="archive",
)
_GETSPLOIT = RequestSpec(
    "GET",
    "/api/v3/archive/getsploit/",
    body_mode="query",
    response_mode="bytes",
    timeout_profile="archive",
)


def _decode_archive(value: Any) -> Any:
    """Return the archive payload parsed as JSON when possible, else raw bytes.

    The body arrives gzip/zip-compressed and is decoded to bytes by the core, then
    parsed as JSON (a collection is a single JSON array). Non-JSON / binary bodies
    pass through as bytes; use :meth:`iter_collection` for lazy, per-element
    streaming of large collections.
    """
    if isinstance(value, (bytes, bytearray)):
        try:
            return orjson.loads(value)
        except orjson.JSONDecodeError:
            return bytes(value)
    return value


def _distributive(value: Any) -> list[Any]:
    # The endpoint returns application/zip whose single member is a bare JSON list
    # of {"_source": ...} objects; the core decodes the zip to those member bytes.
    if isinstance(value, (bytes, bytearray)):
        try:
            value = orjson.loads(value)
        except orjson.JSONDecodeError:
            return []
    if not isinstance(value, list):
        return []
    return [item["_source"] for item in value if isinstance(item, dict) and "_source" in item]


class Archive(_base.BaseResource):
    """Download bulk archives of the Vulners database."""

    def fetch_collection(
        self,
        type: str,
        *,
        timeout: float | httpx.Timeout | NotGiven = not_given,
    ) -> Any:
        """Download an entire collection archive by ``type`` (e.g. ``"cve"``)."""
        return self._request(
            _FETCH_COLLECTION, cast=_decode_archive, body={"type": type}, timeout=timeout
        )

    def iter_collection(
        self,
        type: str,
        *,
        timeout: float | httpx.Timeout | NotGiven = not_given,
    ) -> Iterator[dict[str, Any]]:
        """Stream a collection archive element by element (a JSON array).

        Unlike :meth:`fetch_collection` (which buffers and decodes the whole
        archive), this follows the archive redirect to storage, decompresses the
        body as a stream and yields each array element lazily, so a multi-gigabyte
        collection never has to be held in memory. Each element is a ``dict``.
        """
        for record in self._client.stream_records(
            _STREAM_COLLECTION, params={"type": type}, timeout=timeout
        ):
            yield record

    def fetch_collection_update(
        self,
        type: str,
        after: datetime,
        *,
        timeout: float | httpx.Timeout | NotGiven = not_given,
    ) -> Any:
        """Download only the collection entries changed after ``after``."""
        body = {"type": type, "after": after.isoformat()}
        return self._request(
            _FETCH_COLLECTION_UPDATE, cast=_decode_archive, body=body, timeout=timeout
        )

    def get_collection(
        self,
        type: str,
        *,
        datefrom: str = "1976-01-01",
        dateto: str = "2199-01-01",
        timeout: float | httpx.Timeout | NotGiven = not_given,
    ) -> Any:
        """Download a collection over a date range (legacy v3 endpoint)."""
        body = {"type": type, "datefrom": datefrom, "dateto": dateto}
        return self._request(_GET_COLLECTION, cast=_decode_archive, body=body, timeout=timeout)

    def get_distributive(
        self,
        os: str,
        version: str,
        *,
        timeout: float | httpx.Timeout | NotGiven = not_given,
    ) -> list[Any]:
        """Download the vulnerability distributive for an OS/version (legacy v3)."""
        body = {"os": os, "version": version}
        return self._request(_GET_DISTRIBUTIVE, cast=_distributive, body=body, timeout=timeout)

    def getsploit(
        self,
        *,
        timeout: float | httpx.Timeout | NotGiven = not_given,
    ) -> bytes:
        """Download the raw getsploit exploit database archive (legacy v3)."""
        return self._request(_GETSPLOIT, timeout=timeout)


__all__ = []
