# Do not edit this file directly. It has been autogenerated from
# src/vulners/_resources/_async/search.py
"""Async ``search`` resource (unasyncd source for the sync ``search`` resource).

Representative slice of the search domain: Lucene search returning a typed
:class:`vulners._pagination.SearchPage` (cursor-aware, auto-paginating to the 10k window), an
auto-paginating :meth:`iter_query`, and single / multi document lookup. Rows are
built through :func:`construct_bulletin`, so each row is the family-specific
:class:`Bulletin` subclass for its ``bulletinFamily``.
"""

from __future__ import annotations

import re
from collections.abc import Iterator, Sequence
from typing import Any, Literal

import httpx

from vulners._pagination import SearchPage

from ..._base_client import RequestSpec
from ..._exceptions import SearchWindowExceeded
from ..._models.bulletin import Bulletin, construct_bulletin
from ..._pagination import SEARCH_WINDOW
from ..._types import NotGiven, not_given
from . import _base
from .misc import _AUTOCOMPLETE, _BURP_RULES, _SEARCH_CPE, _SUGGEST, _autocomplete

_SEARCH_SPEC = RequestSpec(
    "POST", "/api/v3/search/lucene/", body_mode="json", unwrap=("data",), idempotent=True
)
_LOOKUP_SPEC = RequestSpec(
    "POST", "/api/v3/search/id/", body_mode="json", unwrap=("data",), idempotent=True
)
_COLLECTIONS_SPEC = RequestSpec("GET", "/api/v4/search/collections", unwrap=("result",))

# A bare CVE id used as a search query must be phrase-quoted, or Lucene
# tokenizes it ("CVE", "2021", "44228") and matches far too much.
_BARE_CVE_RE = re.compile(r"^CVE-\d{4}-\d+$", re.IGNORECASE)


def exploit_search_query(query: str, *, lucene: bool = False) -> str:
    """Build the exploit-family Lucene query for a user query.

    A bare CVE id is phrase-quoted so it matches as one token; when ``lucene``
    is true the query is taken as raw Lucene and only wrapped with the
    ``bulletinFamily:exploit`` filter.
    """
    query = query.strip()
    if not lucene and _BARE_CVE_RE.match(query):
        query = f'"{query}"'
    return f"bulletinFamily:exploit AND ({query})"


# Compact default projection sent when ``fields`` is omitted: the proven v3
# default field set minus the heavy document fields. ``sourceData`` and
# ``description`` can dominate response size on large result pages, so they are
# opt-in — pass ``fields=["*"]`` for whole documents, or name fields explicitly.
DEFAULT_SEARCH_FIELDS: tuple[str, ...] = (
    "id",
    "title",
    "type",
    "bulletinFamily",
    "cvss",
    "published",
    "modified",
    "lastseen",
    "href",
    "sourceHref",
    "cvelist",
    "vulnStatus",
    "assigned",
)


class Search(_base.BaseResource):
    """Search the Vulners database."""

    def query(
        self,
        query: str,
        *,
        limit: int = 20,
        offset: int = 0,
        fields: Sequence[str] | NotGiven = not_given,
        timeout: float | httpx.Timeout | NotGiven = not_given,
    ) -> SearchPage[Bulletin]:
        """Search using Lucene query syntax.

        Args:
            query: A Vulners Lucene query (see https://vulners.com/help).
            limit: Maximum number of documents to return in this page.
            offset: Number of documents to skip.
            fields: Restrict the returned fields. When omitted, the compact
                :data:`DEFAULT_SEARCH_FIELDS` projection is requested; the heavy
                document fields (``sourceData``, ``description``) are opt-in —
                pass ``fields=["*"]`` for whole documents or list fields
                explicitly.

        Returns:
            A cursor-aware :class:`vulners._pagination.SearchPage` of :class:`Bulletin`;
            ``.total`` is the total match count and iterating the page walks
            further pages up to the 10000-document window.

        Raises:
            SearchWindowExceeded: ``offset`` is at or beyond the 10000-document
                window; use the archive API to page further.
        """
        if not query or not query.strip():
            raise ValueError("query must not be empty")
        if limit < 1:
            raise ValueError(f"limit must be >= 1, got {limit}")
        if offset < 0:
            raise ValueError(f"offset must be >= 0, got {offset}")
        if offset >= SEARCH_WINDOW:
            raise SearchWindowExceeded(
                f"offset must be less than {SEARCH_WINDOW} (got {offset}); the search "
                "window is capped at 10000 documents. Use the archive API to retrieve more."
            )
        size = min(limit, SEARCH_WINDOW - offset)
        body: dict[str, Any] = {"query": query, "size": size, "skip": offset}
        body["fields"] = list(DEFAULT_SEARCH_FIELDS if isinstance(fields, NotGiven) else fields)

        def _fetch(next_offset: int, next_size: int) -> SearchPage[Bulletin]:
            return self.query(
                query, limit=next_size, offset=next_offset, fields=fields, timeout=timeout
            )

        def _build(data: Any) -> SearchPage[Bulletin]:
            hits = data.get("search", []) if isinstance(data, dict) else []
            rows = [
                construct_bulletin(hit.get("_source", {}))
                for hit in hits
                if isinstance(hit, dict)
            ]
            total = data.get("total") if isinstance(data, dict) else None
            return SearchPage(data=rows, total=total, offset=offset, limit=size, fetch=_fetch)

        return self._request(_SEARCH_SPEC, cast=_build, body=body, timeout=timeout)

    def iter_query(
        self,
        query: str,
        *,
        page_size: int = 100,
        fields: Sequence[str] | NotGiven = not_given,
        timeout: float | httpx.Timeout | NotGiven = not_given,
    ) -> Iterator[Bulletin]:
        """Iterate every matching :class:`Bulletin`, auto-paginating.

        Fetches pages of ``page_size`` documents and yields their rows lazily,
        stopping at the 10000-document search window. When ``fields`` is
        omitted, the compact :data:`DEFAULT_SEARCH_FIELDS` projection is used
        (heavy fields like ``sourceData``/``description`` are opt-in via
        ``fields=["*"]`` or an explicit list).
        """
        page = self.query(query, limit=page_size, offset=0, fields=fields, timeout=timeout)
        while True:
            for row in page.data:
                yield row
            if not page.has_next_page():
                return
            page = page.next_page()

    def get_multiple_bulletins(
        self,
        ids: Sequence[str],
        *,
        fields: Sequence[str] | NotGiven = not_given,
        references: bool = False,
    ) -> dict[str, Bulletin]:
        """Fetch several documents by id, keyed by id.

        Args:
            ids: Document ids to fetch (e.g. ``CVE-2021-44228``). The returned
                mapping is keyed by these ids; ids with no matching document are
                absent from the result.
            fields: Restrict the returned fields on each document; the server
                default projection is used when omitted.
            references: When ``True``, also resolve and include documents the
                requested bulletins reference/cross-link (e.g. the exploits and
                advisories tied to a CVE); defaults to ``False``.

        Returns:
            A mapping of id to the family-specific :class:`Bulletin`.
        """
        body: dict[str, Any] = {"id": list(ids), "references": references}
        self._set(body, "fields", fields, list)

        def _cast(data: Any) -> dict[str, Bulletin]:
            docs = data.get("documents", {}) if isinstance(data, dict) else {}
            return {
                key: construct_bulletin(value)
                for key, value in docs.items()
                if isinstance(value, dict)
            }

        return self._request(_LOOKUP_SPEC, cast=_cast, body=body)

    def get_bulletin(
        self,
        id: str,
        *,
        fields: Sequence[str] | NotGiven = not_given,
    ) -> Bulletin | None:
        """Fetch a single document by id, or ``None`` if it does not exist.

        Args:
            id: The document id to fetch (e.g. ``CVE-2021-44228``).
            fields: Restrict the returned fields; the server default projection
                is used when omitted.

        Returns:
            The family-specific :class:`Bulletin`, or ``None`` if no document
            matches ``id``.
        """
        body: dict[str, Any] = {"id": [id], "references": False}
        self._set(body, "fields", fields, list)

        def _cast(data: Any) -> Bulletin | None:
            docs = data.get("documents", {}) if isinstance(data, dict) else {}
            raw = docs.get(id)
            return construct_bulletin(raw) if isinstance(raw, dict) else None

        return self._request(_LOOKUP_SPEC, cast=_cast, body=body)

    def exploits(
        self,
        query: str,
        *,
        lucene: bool = False,
        limit: int = 20,
        offset: int = 0,
        fields: Sequence[str] | NotGiven = not_given,
        timeout: float | httpx.Timeout | NotGiven = not_given,
    ) -> SearchPage[Bulletin]:
        """Search for public exploits matching a query.

        Restricts a Lucene search to the ``exploit`` bulletin family. A bare
        CVE id (e.g. ``CVE-2021-44228``) is phrase-quoted automatically so it
        matches as a single token.

        Args:
            query: A CVE id, product name, or Lucene fragment.
            lucene: Treat ``query`` as raw Lucene: no CVE auto-quoting, only
                the exploit-family filter is applied around it.
            limit: Maximum number of documents to return in this page.
            offset: Number of documents to skip.
            fields: Restrict the returned fields, as in :meth:`query`.

        Returns:
            A cursor-aware :class:`vulners._pagination.SearchPage` of :class:`Bulletin`.

        Raises:
            SearchWindowExceeded: ``offset`` is at or beyond the 10000-document
                window.
        """
        return self.query(
            exploit_search_query(query, lucene=lucene),
            limit=limit,
            offset=offset,
            fields=fields,
            timeout=timeout,
        )

    def collections(
        self,
        *,
        timeout: float | httpx.Timeout | NotGiven = not_given,
    ) -> Any:
        """List every collection available in Vulners.

        Returns:
            A list of collection descriptors, each with ``type``, ``count``,
            ``description`` and ``last_updated``, sorted by count descending.
        """
        return self._request(_COLLECTIONS_SPEC, timeout=timeout)

    # -- verb-unified lookups ----------------------------------------------
    # The same endpoints as the ``misc`` resource methods (specs and response
    # handling are shared with that module); surfaced here so every search-ish
    # call is reachable from ``client.search``.

    def autocomplete(
        self,
        query: str,
        *,
        timeout: float | httpx.Timeout | NotGiven = not_given,
    ) -> list[str | list[str]]:
        """Return possible completions for a partial Lucene query.

        Same endpoint as :meth:`Misc.query_autocomplete`.
        """
        return self._request(
            _AUTOCOMPLETE, cast=_autocomplete, body={"query": query}, timeout=timeout
        )

    def suggest(
        self,
        field_name: str,
        *,
        type: Literal["distinct"] = "distinct",
        timeout: float | httpx.Timeout | NotGiven = not_given,
    ) -> Any:
        """Return distinct value suggestions for a document field.

        Same endpoint as :meth:`Misc.get_suggestion`.

        Args:
            field_name: The document field to suggest values for.
            type: Suggestion type; only ``"distinct"`` is supported.
        """
        body = {"fieldName": field_name, "type": type}
        return self._request(_SUGGEST, body=body, timeout=timeout)

    def cpe(
        self,
        product: str,
        *,
        vendor: str | NotGiven = not_given,
        size: int | NotGiven = not_given,
        timeout: float | httpx.Timeout | NotGiven = not_given,
    ) -> Any:
        """Search for CPE strings matching a product (and optional vendor).

        Same endpoint as :meth:`Misc.search_cpe`.

        Args:
            product: Product string to search a CPE for.
            vendor: Optional vendor to narrow the match.
            size: Maximum number of results (0..10000, ``0`` means all).
        """
        body: dict[str, Any] = {"product": product}
        self._set(body, "vendor", vendor)
        self._set(body, "size", size)
        return self._request(_SEARCH_CPE, body=body, timeout=timeout)

    def web_vulns(
        self,
        *,
        timeout: float | httpx.Timeout | NotGiven = not_given,
    ) -> Any:
        """Return the Vulners web-application (burp) detection rule set.

        Same endpoint as :meth:`Misc.get_web_application_rules`.
        """
        return self._request(_BURP_RULES, timeout=timeout)


__all__ = []
