# Do not edit this file directly. It has been autogenerated from
# src/vulners/_resources/_async/search.py
"""Async ``search`` resource (unasyncd source for the sync ``search`` resource).

Representative slice of the search domain: Lucene search returning a typed
:class:`vulners._pagination.SearchPage` (cursor-aware, auto-paginating to the 10k window), an
auto-paginating :meth:`iter_query`, and single / multi document lookup. Rows are
built through :func:`construct_bulletin`, so each row is the family-specific
:class:`Bulletin` subclass for its ``bulletinFamily``.
"""

from __future__ import annotations

from collections.abc import Iterator, Sequence
from typing import Any

import httpx

from vulners._pagination import SearchPage

from ..._base_client import RequestSpec
from ..._exceptions import SearchWindowExceeded
from ..._models.bulletin import Bulletin, construct_bulletin
from ..._pagination import SEARCH_WINDOW
from ..._types import NotGiven, not_given
from . import _base

_SEARCH_SPEC = RequestSpec(
    "POST", "/api/v3/search/lucene/", body_mode="json", unwrap=("data",), idempotent=True
)
_LOOKUP_SPEC = RequestSpec(
    "POST", "/api/v3/search/id/", body_mode="json", unwrap=("data",), idempotent=True
)


class Search(_base.BaseResource):
    """Search the Vulners database."""

    def query(
        self,
        query: str,
        *,
        limit: int = 20,
        offset: int = 0,
        fields: Sequence[str] | NotGiven = not_given,
        timeout: float | httpx.Timeout | NotGiven = not_given,
    ) -> SearchPage[Bulletin]:
        """Search using Lucene query syntax.

        Args:
            query: A Vulners Lucene query (see https://vulners.com/help).
            limit: Maximum number of documents to return in this page.
            offset: Number of documents to skip.
            fields: Restrict the returned fields; the server default is used when
                omitted.

        Returns:
            A cursor-aware :class:`vulners._pagination.SearchPage` of :class:`Bulletin`;
            ``.total`` is the total match count and iterating the page walks
            further pages up to the 10000-document window.

        Raises:
            SearchWindowExceeded: ``offset`` is at or beyond the 10000-document
                window; use the archive API to page further.
        """
        if offset >= SEARCH_WINDOW:
            raise SearchWindowExceeded(
                f"offset must be less than {SEARCH_WINDOW} (got {offset}); the search "
                "window is capped at 10000 documents. Use the archive API to retrieve more."
            )
        size = min(limit, SEARCH_WINDOW - offset)
        body: dict[str, Any] = {"query": query, "size": size, "skip": offset}
        if not isinstance(fields, NotGiven):
            body["fields"] = list(fields)

        def _fetch(next_offset: int, next_size: int) -> SearchPage[Bulletin]:
            return self.query(
                query, limit=next_size, offset=next_offset, fields=fields, timeout=timeout
            )

        def _build(data: Any) -> SearchPage[Bulletin]:
            hits = data.get("search", []) if isinstance(data, dict) else []
            rows = [
                construct_bulletin(hit.get("_source", {}))
                for hit in hits
                if isinstance(hit, dict)
            ]
            total = data.get("total") if isinstance(data, dict) else None
            return SearchPage(data=rows, total=total, offset=offset, limit=size, fetch=_fetch)

        return self._request(_SEARCH_SPEC, cast=_build, body=body, timeout=timeout)

    def iter_query(
        self,
        query: str,
        *,
        page_size: int = 100,
        fields: Sequence[str] | NotGiven = not_given,
        timeout: float | httpx.Timeout | NotGiven = not_given,
    ) -> Iterator[Bulletin]:
        """Iterate every matching :class:`Bulletin`, auto-paginating.

        Fetches pages of ``page_size`` documents and yields their rows lazily,
        stopping at the 10000-document search window.
        """
        page = self.query(query, limit=page_size, offset=0, fields=fields, timeout=timeout)
        while True:
            for row in page.data:
                yield row
            if not page.has_next_page():
                return
            page = page.next_page()

    def get_multiple_bulletins(
        self,
        ids: Sequence[str],
        *,
        fields: Sequence[str] | NotGiven = not_given,
        references: bool = False,
    ) -> dict[str, Bulletin]:
        """Fetch several documents by id, keyed by id."""
        body: dict[str, Any] = {"id": list(ids), "references": references}
        if not isinstance(fields, NotGiven):
            body["fields"] = list(fields)

        def _cast(data: Any) -> dict[str, Bulletin]:
            docs = data.get("documents", {}) if isinstance(data, dict) else {}
            return {
                key: construct_bulletin(value)
                for key, value in docs.items()
                if isinstance(value, dict)
            }

        return self._request(_LOOKUP_SPEC, cast=_cast, body=body)

    def get_bulletin(
        self,
        id: str,
        *,
        fields: Sequence[str] | NotGiven = not_given,
    ) -> Bulletin | None:
        """Fetch a single document by id, or ``None`` if it does not exist."""
        body: dict[str, Any] = {"id": [id], "references": False}
        if not isinstance(fields, NotGiven):
            body["fields"] = list(fields)

        def _cast(data: Any) -> Bulletin | None:
            docs = data.get("documents", {}) if isinstance(data, dict) else {}
            raw = docs.get(id)
            return construct_bulletin(raw) if isinstance(raw, dict) else None

        return self._request(_LOOKUP_SPEC, cast=_cast, body=body)


__all__ = []
