# Do not edit this file directly. It has been autogenerated from
# src/vulners/_resources/_async/subscriptions.py
"""Async ``subscriptions`` resource (v3 email subscriptions).

Unasyncd source for the sync ``subscriptions`` resource. These are the legacy v3
email-subscription endpoints; the newer JSON-delivery subscriptions live on the
``subscriptions_v4`` resource.
"""

from __future__ import annotations

from typing import Any, Literal

import httpx

from ..._base_client import RequestSpec
from ..._types import NotGiven, not_given
from . import _base

_LIST = RequestSpec(
    "GET",
    "/api/v3/subscriptions/listEmailSubscriptions/",
    body_mode="query",
    unwrap=("data", "subscriptions"),
)
_ADD = RequestSpec(
    "POST", "/api/v3/subscriptions/addEmailSubscription/", body_mode="json", unwrap=("data",)
)
_EDIT = RequestSpec(
    "POST", "/api/v3/subscriptions/editEmailSubscription/", body_mode="json", unwrap=("data",)
)
_DELETE = RequestSpec(
    "POST", "/api/v3/subscriptions/removeEmailSubscription/", body_mode="json", unwrap=("data",)
)


class Subscriptions(_base.BaseResource):
    """Manage v3 email subscriptions.

    The ``api_key`` argument on the mutating methods names the *owner* of the
    subscription (sent in the body as ``apiKey``) and defaults to the client's
    own key. A privileged key sent in the ``X-Api-Key`` header can pass a
    different owner key to manage that key's subscriptions.
    """

    def list(
        self,
        *,
        timeout: float | httpx.Timeout | NotGiven = not_given,
    ) -> Any:
        """List the account's email subscriptions."""
        return self._request(_LIST, timeout=timeout)

    def add(
        self,
        *,
        query: str,
        email: str,
        format: Literal["html", "json", "pdf"] = "html",
        crontab: str | NotGiven = not_given,
        query_type: str = "lucene",
        api_key: str | None = None,
        timeout: float | httpx.Timeout | NotGiven = not_given,
    ) -> Any:
        """Create an email subscription for a query.

        Args:
            query: The search query to subscribe to.
            email: Destination email address.
            format: Report format, ``"html"``, ``"json"`` or ``"pdf"``.
            crontab: Optional crontab schedule.
            query_type: Query language, defaults to ``"lucene"``.
            api_key: Owner key for the subscription. Defaults to the client's
                own key; pass another key (with a privileged key on the client)
                to create the subscription under that key.
        """
        body: dict[str, Any] = {
            "query": query,
            "email": email,
            "format": format,
            "query_type": query_type,
        }
        self._set(body, "crontab", crontab)
        body["apiKey"] = api_key or self._api_key
        return self._request(_ADD, body=body, timeout=timeout)

    def edit(
        self,
        subscription_id: str,
        *,
        format: Literal["html", "json", "pdf"] | NotGiven = not_given,
        crontab: str | NotGiven = not_given,
        active: Literal["yes", "no", "true", "false"] | NotGiven = not_given,
        api_key: str | None = None,
        timeout: float | httpx.Timeout | NotGiven = not_given,
    ) -> Any:
        """Edit an existing email subscription.

        Args:
            subscription_id: The subscription to edit.
            format: New report format, if changing.
            crontab: New crontab schedule, if changing.
            active: New active state, if changing.
            api_key: Owner key for the subscription (see :meth:`add`).
        """
        body: dict[str, Any] = {"subscriptionid": subscription_id}
        self._set(body, "format", format)
        self._set(body, "crontab", crontab)
        self._set(body, "active", active)
        body["apiKey"] = api_key or self._api_key
        return self._request(_EDIT, body=body, timeout=timeout)

    def delete(
        self,
        subscription_id: str,
        *,
        api_key: str | None = None,
        timeout: float | httpx.Timeout | NotGiven = not_given,
    ) -> Any:
        """Delete an email subscription.

        Args:
            subscription_id: The subscription to delete.
            api_key: Owner key for the subscription (see :meth:`add`).
        """
        body = {"subscriptionid": subscription_id, "apiKey": api_key or self._api_key}
        return self._request(_DELETE, body=body, timeout=timeout)


__all__ = []
