# Do not edit this file directly. It has been autogenerated from
# src/vulners/_resources/_async/vscanner.py
"""Async ``vscanner`` resource (unasyncd source for the sync ``vscanner`` resource).

VScanner is a separate Vulners product surfaced here as a namespaced resource:
``vscanner.licenses``, ``vscanner.projects``, ``vscanner.projects.tasks`` and
``vscanner.projects.results``. Id parameters are typed as :class:`uuid.UUID` in
signatures (accepting the canonical string form at runtime).
"""

from __future__ import annotations

import base64
import posixpath
import uuid
from collections.abc import Mapping, Sequence
from functools import cached_property
from typing import Any, Literal
from urllib.parse import quote, unquote, urlsplit

import httpx

from ..._base_client import BodyMode, RequestSpec, ResponseMode
from ..._types import NotGiven, not_given
from . import _base

# All VScanner calls share one rate-limit bucket, matching the v3 client.
_GROUP = "vscanner"
_ROOT = "/api/v3/proxy/vscanner/v2/projects"
# Upper bound on percent-decode passes when validating a screenshot uri; a real
# uri stabilises in one or two passes, the cap stops pathological nesting.
_MAX_DECODE_PASSES = 40

_LICENSES = RequestSpec(
    "GET",
    "/api/v3/useraction/licenseids",
    body_mode="query",
    unwrap=("data",),
    ratelimit_group=_GROUP,
)


def _seg(value: Any) -> str:
    """Percent-quote a single path segment so an id cannot retarget the URL."""
    return quote(str(value), safe="")


def _spec(
    method: str, path: str, *, body_mode: BodyMode = "query", response_mode: ResponseMode = "json"
) -> RequestSpec:
    return RequestSpec(
        method,
        path,
        body_mode=body_mode,
        response_mode=response_mode,
        unwrap=() if response_mode == "bytes" else ("data",),
        ratelimit_group=_GROUP,
    )


def _guard_screenshot_path(url_path: str) -> None:
    """Reject a screenshot uri whose normalized path escapes /vscanner/screen/."""
    decoded = urlsplit(url_path).path
    for _ in range(_MAX_DECODE_PASSES):
        once = unquote(decoded)
        if once == decoded:
            break
        decoded = once
    else:
        raise ValueError("Invalid image_uri: excessive percent-encoding")
    decoded = decoded.replace("\\", "/")
    if not posixpath.normpath(decoded).startswith("/vscanner/screen/"):
        raise ValueError("Invalid image_uri: path must stay under /vscanner/screen/")


class VscannerLicenses(_base.BaseResource):
    """VScanner license ids."""

    def list(
        self,
        *,
        timeout: float | httpx.Timeout | NotGiven = not_given,
    ) -> Any:
        """Return the account's VScanner license ids."""
        return self._request(_LICENSES, timeout=timeout)


class VscannerTasks(_base.BaseResource):
    """Scan tasks within a VScanner project."""

    def list(
        self,
        project_id: uuid.UUID,
        *,
        offset: int = 0,
        limit: int = 50,
        timeout: float | httpx.Timeout | NotGiven = not_given,
    ) -> Any:
        """List a project's tasks."""
        spec = _spec("GET", f"{_ROOT}/{_seg(project_id)}/tasks")
        return self._request(spec, body={"offset": offset, "limit": limit}, timeout=timeout)

    def create(
        self,
        project_id: uuid.UUID,
        *,
        name: str,
        networks: Sequence[str],
        ports: Sequence[str],
        schedule: str,
        timing: str,
        enabled: bool,
        timeout: float | httpx.Timeout | NotGiven = not_given,
    ) -> Any:
        """Create a scan task in a project.

        Args:
            project_id: The owning project.
            name: Task name.
            networks: Networks to scan (ips or domains).
            ports: Ports or port ranges.
            schedule: Crontab schedule string.
            timing: Scan timing profile.
            enabled: Whether the task is enabled.
        """
        body = {
            "name": name,
            "networks": list(networks),
            "ports": list(ports),
            "schedule": schedule,
            "timing": timing,
            "enabled": enabled,
        }
        spec = _spec("POST", f"{_ROOT}/{_seg(project_id)}/tasks", body_mode="json")
        return self._request(spec, body=body, timeout=timeout)

    def update(
        self,
        project_id: uuid.UUID,
        task_id: uuid.UUID,
        *,
        name: str,
        networks: Sequence[str],
        ports: Sequence[str],
        schedule: str,
        timing: str,
        enabled: bool,
        timeout: float | httpx.Timeout | NotGiven = not_given,
    ) -> Any:
        """Update a scan task (full replace)."""
        body = {
            "name": name,
            "networks": list(networks),
            "ports": list(ports),
            "schedule": schedule,
            "timing": timing,
            "enabled": enabled,
        }
        spec = _spec("PUT", f"{_ROOT}/{_seg(project_id)}/tasks/{_seg(task_id)}", body_mode="json")
        return self._request(spec, body=body, timeout=timeout)

    def start(
        self,
        project_id: uuid.UUID,
        task_id: uuid.UUID,
        *,
        timeout: float | httpx.Timeout | NotGiven = not_given,
    ) -> Any:
        """Start a task as soon as possible."""
        spec = _spec(
            "POST", f"{_ROOT}/{_seg(project_id)}/tasks/{_seg(task_id)}/start", body_mode="json"
        )
        return self._request(spec, timeout=timeout)

    def delete(
        self,
        project_id: uuid.UUID,
        task_id: uuid.UUID,
        *,
        timeout: float | httpx.Timeout | NotGiven = not_given,
    ) -> Any:
        """Delete a task."""
        spec = _spec("DELETE", f"{_ROOT}/{_seg(project_id)}/tasks/{_seg(task_id)}")
        return self._request(spec, timeout=timeout)


class VscannerResults(_base.BaseResource):
    """Scan results and screenshots within a VScanner project."""

    def list(
        self,
        project_id: uuid.UUID,
        *,
        search: str | NotGiven = not_given,
        in_port: Sequence[str] | NotGiven = not_given,
        ex_port: Sequence[str] | NotGiven = not_given,
        min_cvss: float | NotGiven = not_given,
        max_cvss: float | NotGiven = not_given,
        last_seen: int | NotGiven = not_given,
        first_seen: int | NotGiven = not_given,
        last_seen_port: int | NotGiven = not_given,
        first_seen_port: int | NotGiven = not_given,
        sort: Literal[
            "ip", "name", "last_seen", "first_seen", "resolved", "min_cvss", "max_cvss"
        ] = "last_seen",
        sort_dir: Literal["asc", "desc"] = "asc",
        offset: int = 0,
        limit: int = 50,
        timeout: float | httpx.Timeout | NotGiven = not_given,
    ) -> Any:
        """List a project's scan results, with optional filtering and sorting."""
        body: dict[str, Any] = {
            "sort": sort,
            "sort_dir": sort_dir,
            "offset": offset,
            "limit": limit,
        }
        self._set(body, "search", search)
        self._set(body, "in_port", in_port, list)
        self._set(body, "ex_port", ex_port, list)
        self._set(body, "min_cvss", min_cvss)
        self._set(body, "max_cvss", max_cvss)
        self._set(body, "last_seen", last_seen)
        self._set(body, "first_seen", first_seen)
        self._set(body, "last_seen_port", last_seen_port)
        self._set(body, "first_seen_port", first_seen_port)
        spec = _spec("GET", f"{_ROOT}/{_seg(project_id)}/results")
        return self._request(spec, body=body, timeout=timeout)

    def delete(
        self,
        project_id: uuid.UUID,
        result_id: uuid.UUID,
        *,
        timeout: float | httpx.Timeout | NotGiven = not_given,
    ) -> Any:
        """Delete a single scan result."""
        spec = _spec("DELETE", f"{_ROOT}/{_seg(project_id)}/results/{_seg(result_id)}")
        return self._request(spec, timeout=timeout)

    def screenshot(
        self,
        image_uri: str,
        *,
        as_base64: bool = False,
        timeout: float | httpx.Timeout | NotGiven = not_given,
    ) -> bytes:
        """Download a result screenshot as bytes.

        Args:
            image_uri: The server-provided screenshot uri (from a result's
                ``screens``). It is validated to stay under ``/vscanner/screen/``.
            as_base64: Return base64-encoded bytes instead of raw bytes.
        """
        url = "/vscanner/screen/" + image_uri
        _guard_screenshot_path(url)
        spec = _spec("GET", url, response_mode="bytes")
        content: bytes = self._request(spec, timeout=timeout)
        return base64.b64encode(content) if as_base64 else content


class VscannerProjects(_base.BaseResource):
    """VScanner projects, plus their tasks and results namespaces."""

    @cached_property
    def tasks(self) -> VscannerTasks:
        return VscannerTasks(self._client)

    @cached_property
    def results(self) -> VscannerResults:
        return VscannerResults(self._client)

    def list(
        self,
        *,
        offset: int = 0,
        limit: int = 50,
        timeout: float | httpx.Timeout | NotGiven = not_given,
    ) -> Any:
        """List the account's projects."""
        spec = _spec("GET", f"{_ROOT}/")
        return self._request(spec, body={"offset": offset, "limit": limit}, timeout=timeout)

    def create(
        self,
        *,
        name: str,
        license_id: uuid.UUID,
        notification: Mapping[str, Any],
        result_expire_in: int | None | NotGiven = not_given,
        timeout: float | httpx.Timeout | NotGiven = not_given,
    ) -> Any:
        """Create a project.

        Args:
            name: New project name.
            license_id: The license id to use.
            notification: A notification object (see
                :meth:`Vscanner.notification`).
            result_expire_in: Expire results after N days; ``None`` never expires.
        """
        body: dict[str, Any] = {
            "name": name,
            "license_id": str(license_id),
            "notification": dict(notification),
        }
        self._set(body, "result_expire_in", result_expire_in)
        spec = _spec("POST", f"{_ROOT}/", body_mode="json")
        return self._request(spec, body=body, timeout=timeout)

    def update(
        self,
        project_id: uuid.UUID,
        *,
        name: str,
        license_id: uuid.UUID,
        notification: Mapping[str, Any],
        result_expire_in: int | None,
        timeout: float | httpx.Timeout | NotGiven = not_given,
    ) -> Any:
        """Update a project (full replace)."""
        body = {
            "name": name,
            "license_id": str(license_id),
            "notification": dict(notification),
            "result_expire_in": result_expire_in,
        }
        spec = _spec("PUT", f"{_ROOT}/{_seg(project_id)}", body_mode="json")
        return self._request(spec, body=body, timeout=timeout)

    def delete(
        self,
        project_id: uuid.UUID,
        *,
        timeout: float | httpx.Timeout | NotGiven = not_given,
    ) -> Any:
        """Delete a project."""
        spec = _spec("DELETE", f"{_ROOT}/{_seg(project_id)}")
        return self._request(spec, timeout=timeout)

    def statistics(
        self,
        project_id: uuid.UUID,
        *,
        stat: Sequence[
            Literal[
                "total_hosts",
                "vulnerable_hosts",
                "unique_cve",
                "min_max_cvss",
                "vulnerabilities_rank",
                "vulnerable_hosts_rank",
            ]
        ],
        timeout: float | httpx.Timeout | NotGiven = not_given,
    ) -> Any:
        """Return project statistics for the requested aggregations."""
        spec = _spec("GET", f"{_ROOT}/{_seg(project_id)}/statistic")
        return self._request(spec, body={"stat": list(stat)}, timeout=timeout)


class Vscanner(_base.BaseResource):
    """VScanner product namespace on the client."""

    @cached_property
    def licenses(self) -> VscannerLicenses:
        return VscannerLicenses(self._client)

    @cached_property
    def projects(self) -> VscannerProjects:
        return VscannerProjects(self._client)

    @staticmethod
    def notification(
        period: Literal["disabled", "asap", "hourly", "daily"],
        emails: Sequence[str] | None = None,
        slack_webhooks: Sequence[str] | None = None,
    ) -> dict[str, Any]:
        """Build a notification object for a project.

        Args:
            period: One of ``"disabled"``, ``"asap"``, ``"hourly"``, ``"daily"``.
            emails: Email destinations.
            slack_webhooks: Slack webhook destinations.
        """
        if period not in ("disabled", "asap", "hourly", "daily"):
            raise ValueError(
                'period expected to be one of "disabled", "asap", "hourly" or "daily"'
            )
        return {
            "period": period,
            "email": list(emails or []),
            "slack": list(slack_webhooks or []),
        }

    @staticmethod
    def disabled_notification() -> dict[str, Any]:
        """Build a stub notification object with ``"disabled"`` period."""
        return {"period": "disabled", "email": [], "slack": []}


__all__ = []
