"""Response models and the recursive validation-free constructor."""

from __future__ import annotations

from ._base import Discriminator, VulnersModel, construct_type, register_discriminator
from .bulletin import (
    AdvisoryBulletin,
    BugBountyBulletin,
    Bulletin,
    CveBulletin,
    Cvss,
    Cvss2,
    Cvss3,
    Cvss4,
    Enchantments,
    EpssScore,
    ExploitBulletin,
    GenericBulletin,
    InfoBulletin,
    LibraryBulletin,
    MicrosoftBulletin,
    ScannerBulletin,
    SoftwareBulletin,
    Timestamps,
    UnixBulletin,
    bulletin_class_for,
    construct_bulletin,
)

__all__ = [
    "AdvisoryBulletin",
    "BugBountyBulletin",
    "Bulletin",
    "CveBulletin",
    "Cvss",
    "Cvss2",
    "Cvss3",
    "Cvss4",
    "Discriminator",
    "Enchantments",
    "EpssScore",
    "ExploitBulletin",
    "GenericBulletin",
    "InfoBulletin",
    "LibraryBulletin",
    "MicrosoftBulletin",
    "ScannerBulletin",
    "SoftwareBulletin",
    "Timestamps",
    "UnixBulletin",
    "VulnersModel",
    "bulletin_class_for",
    "construct_bulletin",
    "construct_type",
    "register_discriminator",
]
