"""Per-collection field data — GENERATED, do not edit.

Maps a collection ``type`` to ``{"family": <bulletinFamily>, "fields": {<wire>:
<type token>}}`` — the fields it adds beyond its family model. Consumed by the
lazy model factory in :mod:`.collections`. Regenerate from live data with::

    python dev-tools/data-models/sample_collections.py            # sample
    python dev-tools/data-models/sample_collections.py --emit-models
"""

# fmt: off
# ruff: noqa: E501 - one compact line per collection by design

COLLECTIONS: dict[str, dict] = {
    "0daydb": {"family": "exploit", "fields": {}},
    "adobe": {"family": "software", "fields": {}},
    "aix": {"family": "unix", "fields": {"aixFileset": "list"}},
    "akamaiblog": {"family": "blog", "fields": {}},
    "almalinux": {"family": "unix", "fields": {}},
    "alpinelinux": {"family": "unix", "fields": {}},
    "altlinux": {"family": "unix", "fields": {}},
    "amazon": {"family": "unix", "fields": {}},
    "amd": {"family": "info", "fields": {}},
    "anandpraka": {"family": "blog", "fields": {}},
    "android": {"family": "software", "fields": {}},
    "androidsecurity": {"family": "software", "fields": {}},
    "anthropic": {"family": "software", "fields": {}},
    "appercut": {"family": "software", "fields": {"appercut": "any"}},
    "apple": {"family": "software", "fields": {}},
    "archlinux": {"family": "unix", "fields": {}},
    "arista": {"family": "software", "fields": {}},
    "astralinux": {"family": "unix", "fields": {}},
    "atlassian": {"family": "software", "fields": {}},
    "attackerkb": {"family": "info", "fields": {"attackerkb": "any", "cpeConfigurations": "any", "last_activity": "str", "references_categories": "any"}},
    "avleonov": {"family": "blog", "fields": {}},
    "bdu_fstec": {"family": "info", "fields": {"cpeConfigurations": "any"}},
    "binamuse": {"family": "info", "fields": {}},
    "brave": {"family": "software", "fields": {}},
    "broadcom": {"family": "software", "fields": {}},
    "cakephp": {"family": "software", "fields": {}},
    "canvas": {"family": "exploit", "fields": {}},
    "carbonblack": {"family": "blog", "fields": {}},
    "cbl_mariner": {"family": "unix", "fields": {}},
    "centos": {"family": "unix", "fields": {}},
    "cert": {"family": "info", "fields": {}},
    "cgr": {"family": "unix", "fields": {}},
    "checkpoint_advisories": {"family": "info", "fields": {"protected_by": "list", "vulnerable_products": "list"}},
    "checkpoint_security": {"family": "software", "fields": {}},
    "chrome": {"family": "software", "fields": {}},
    "circl": {"family": "info", "fields": {"items": "list"}},
    "cisa": {"family": "info", "fields": {}},
    "cisa_kev": {"family": "info", "fields": {"dueDate": "str", "notes": "str", "product": "str", "requiredAction": "str", "vendor": "str"}},
    "cisco": {"family": "software", "fields": {"vendorCvss": "any"}},
    "ciscothreats": {"family": "info", "fields": {"ciscoThreat": "any"}},
    "citrix": {"family": "software", "fields": {}},
    "clickhouse": {"family": "software", "fields": {}},
    "cloudfoundry": {"family": "software", "fields": {}},
    "cloudlinux": {"family": "unix", "fields": {}},
    "cnnvd": {"family": "cnnvd", "fields": {}},
    "cnvd": {"family": "cnvd", "fields": {}},
    "coalfire": {"family": "blog", "fields": {}},
    "code423n4": {"family": "crypto", "fields": {"vendor_severity": "str"}},
    "contao": {"family": "software", "fields": {}},
    "coresecurity": {"family": "info", "fields": {}},
    "curl": {"family": "software", "fields": {"curlAffects": "str", "curlSeverity": "str"}},
    "cve": {"family": "cve", "fields": {"assigned": "str", "extraReferences": "list", "origin": "str"}},
    "cve0day": {"family": "info", "fields": {}},
    "cvelist": {"family": "cve", "fields": {"assigned": "str", "dateUpdated": "str", "origin": "str", "provider": "str"}},
    "d0znpp": {"family": "blog", "fields": {}},
    "d2": {"family": "exploit", "fields": {}},
    "debian": {"family": "unix", "fields": {}},
    "debiancve": {"family": "unix", "fields": {}},
    "drupal": {"family": "software", "fields": {}},
    "dsquare": {"family": "exploit", "fields": {}},
    "duo": {"family": "info", "fields": {}},
    "elastic": {"family": "software", "fields": {}},
    "erpscan": {"family": "info", "fields": {}},
    "euvd": {"family": "euvd", "fields": {"cnaAffected": "list"}},
    "exploitdb": {"family": "exploit", "fields": {}},
    "exploitpack": {"family": "exploit", "fields": {"exploitpack": "any"}},
    "f5": {"family": "software", "fields": {"related": "list"}},
    "fedora": {"family": "unix", "fields": {}},
    "filippoio": {"family": "blog", "fields": {}},
    "fireeye": {"family": "info", "fields": {}},
    "fortinet": {"family": "software", "fields": {}},
    "freebsd": {"family": "unix", "fields": {}},
    "freebsd_advisory": {"family": "unix", "fields": {}},
    "friendsofphp": {"family": "software", "fields": {}},
    "fuelphp": {"family": "software", "fields": {}},
    "gentoo": {"family": "unix", "fields": {}},
    "gitee": {"family": "exploit", "fields": {"exploitProbabilityScoring": "any"}},
    "github": {"family": "software", "fields": {}},
    "githubexploit": {"family": "exploit", "fields": {"exploitProbabilityScoring": "any"}},
    "gitlab": {"family": "software", "fields": {"cweIds": "list", "vendorCvss3": "str"}},
    "googleprojectzero": {"family": "info", "fields": {}},
    "grafana": {"family": "software", "fields": {"vendorCvss": "any"}},
    "hackapp": {"family": "software", "fields": {"hackapp": "any"}},
    "hackerone": {"family": "bugbounty", "fields": {"h1reporter": "any", "h1team": "any"}},
    "hackread": {"family": "blog", "fields": {}},
    "hashicorp": {"family": "software", "fields": {"hashicorpBulletinId": "str", "hashicorpProducts": "any"}},
    "hivepro": {"family": "info", "fields": {}},
    "hp": {"family": "software", "fields": {}},
    "hpe": {"family": "software", "fields": {"vendorCvss": "any"}},
    "htbridge": {"family": "software", "fields": {}},
    "httpd": {"family": "software", "fields": {}},
    "huawei": {"family": "software", "fields": {}},
    "huntr": {"family": "bugbounty", "fields": {"language": "str", "patch_commit_sha": "str", "status": "str"}},
    "ibm": {"family": "software", "fields": {}},
    "ics": {"family": "info", "fields": {}},
    "impervablog": {"family": "blog", "fields": {}},
    "intel": {"family": "info", "fields": {}},
    "intothesymmetry": {"family": "blog", "fields": {}},
    "ivanti": {"family": "software", "fields": {}},
    "jakearchibald": {"family": "blog", "fields": {}},
    "jenkins": {"family": "software", "fields": {"jenkinsAdvisoryId": "str", "jenkinsKind": "str", "jenkinsPlugins": "any", "jenkinsReporter": "str", "vendorCvss": "any"}},
    "jetbrains": {"family": "software", "fields": {}},
    "joomla": {"family": "software", "fields": {}},
    "jvn": {"family": "jvn", "fields": {}},
    "kaspersky": {"family": "info", "fields": {}},
    "kitploit": {"family": "tools", "fields": {"toolHref": "str"}},
    "korelogic": {"family": "software", "fields": {}},
    "krebs": {"family": "blog", "fields": {}},
    "kubernetes": {"family": "software", "fields": {"kubernetesIssueNumber": "int", "kubernetesStatus": "str", "vendorCvss": "any"}},
    "laminas": {"family": "software", "fields": {}},
    "lenovo": {"family": "info", "fields": {}},
    "mageia": {"family": "unix", "fields": {}},
    "malwarebytes": {"family": "blog", "fields": {}},
    "mariadbunix": {"family": "unix", "fields": {"unofficial_repo": "bool"}},
    "metasploit": {"family": "exploit", "fields": {}},
    "mmpc": {"family": "blog", "fields": {}},
    "modx": {"family": "software", "fields": {}},
    "mongodb": {"family": "software", "fields": {}},
    "mozilla": {"family": "software", "fields": {}},
    "mscve": {"family": "microsoft", "fields": {"cpeConfigurations": "any", "customerActionRequired": "bool", "denialOfService": "str", "faq": "list", "issuingCna": "str", "msDetailRevision": "str", "mscve": "str", "tag": "str", "vendorCvss": "any"}},
    "mskb": {"family": "microsoft", "fields": {"affectedProducts": "any", "mscve": "str", "msfamily": "str", "msimpact": "str", "msproducts": "any"}},
    "msrc": {"family": "blog", "fields": {}},
    "mssecure": {"family": "blog", "fields": {}},
    "msupdate": {"family": "microsoft", "fields": {"bundledUpdates": "list", "prerequisitesUpdates": "list", "revision": "str", "supersededUpdates": "list"}},
    "msvr": {"family": "software", "fields": {}},
    "myhack58": {"family": "info", "fields": {}},
    "n0where": {"family": "tools", "fields": {"toolHref": "str"}},
    "ncsc": {"family": "ncsc", "fields": {}},
    "nessus": {"family": "scanner", "fields": {"exploitEase": "str", "patchPublicationDate": "str", "vendor_cvss2": "any", "vendor_cvss3": "any", "vulnerabilityPublicationDate": "str"}},
    "nextcloud": {"family": "software", "fields": {}},
    "nginx": {"family": "software", "fields": {}},
    "nmap": {"family": "scanner", "fields": {"nmap": "any"}},
    "nodejs": {"family": "software", "fields": {}},
    "nodejsblog": {"family": "software", "fields": {}},
    "nozomi": {"family": "nozomi", "fields": {}},
    "nuclei": {"family": "scanner", "fields": {}},
    "nvd": {"family": "cve", "fields": {"origin": "str", "source_references": "list"}},
    "nvidia": {"family": "software", "fields": {}},
    "openbugbounty": {"family": "bugbounty", "fields": {"openbugbounty": "any"}},
    "openssl": {"family": "software", "fields": {}},
    "opensuse": {"family": "unix", "fields": {}},
    "openvas": {"family": "scanner", "fields": {}},
    "openwrt": {"family": "unix", "fields": {}},
    "opera": {"family": "software", "fields": {}},
    "oracle": {"family": "software", "fields": {}},
    "oraclelinux": {"family": "unix", "fields": {}},
    "ossf": {"family": "software", "fields": {}},
    "ossfuzz": {"family": "software", "fields": {"ossfuzz": "any"}},
    "osv": {"family": "library", "fields": {"osvCrossReferences": "any", "osvPackages": "any", "osvSeverity": "any"}},
    "owncloud": {"family": "software", "fields": {}},
    "packetstorm": {"family": "exploit", "fields": {}},
    "packetstormnews": {"family": "info", "fields": {}},
    "paloalto": {"family": "software", "fields": {}},
    "patchstack": {"family": "software", "fields": {"classification": "str", "isExploited": "bool", "owasp": "str"}},
    "pentestit": {"family": "blog", "fields": {}},
    "pentestlab": {"family": "blog", "fields": {}},
    "pentestnepal": {"family": "blog", "fields": {}},
    "pentestpartners": {"family": "blog", "fields": {}},
    "photon": {"family": "unix", "fields": {"vendorCvss": "any"}},
    "phpmyadmin": {"family": "software", "fields": {}},
    "postgresql": {"family": "software", "fields": {}},
    "prion": {"family": "cve", "fields": {}},
    "ptsecurity": {"family": "info", "fields": {}},
    "pwnmalw": {"family": "exploit", "fields": {}},
    "pypa": {"family": "software", "fields": {}},
    "qt": {"family": "info", "fields": {}},
    "qualysblog": {"family": "blog", "fields": {}},
    "rapid7blog": {"family": "info", "fields": {}},
    "rapid7community": {"family": "blog", "fields": {}},
    "rdot": {"family": "info", "fields": {}},
    "redhat": {"family": "unix", "fields": {"relatesTo": "str"}},
    "redhatcve": {"family": "info", "fields": {"sourceAffectedData": "any", "vendorCvss": "any"}},
    "redos": {"family": "unix", "fields": {}},
    "rhino": {"family": "blog", "fields": {}},
    "ripstech": {"family": "blog", "fields": {}},
    "rocky": {"family": "unix", "fields": {}},
    "rosalinux": {"family": "unix", "fields": {}},
    "rubygems": {"family": "software", "fields": {}},
    "rustsec": {"family": "software", "fields": {}},
    "saint": {"family": "exploit", "fields": {}},
    "samba": {"family": "info", "fields": {}},
    "schneier": {"family": "blog", "fields": {}},
    "securelist": {"family": "blog", "fields": {}},
    "security_vulns": {"family": "info", "fields": {}},
    "securityvulns": {"family": "software", "fields": {}},
    "seebug": {"family": "exploit", "fields": {"status": "str"}},
    "sick": {"family": "software", "fields": {}},
    "silentrobots": {"family": "blog", "fields": {}},
    "slackware": {"family": "unix", "fields": {}},
    "snyk": {"family": "library", "fields": {"cpeConfigurations": "any", "snykData": "any"}},
    "sonarsource": {"family": "blog", "fields": {}},
    "sonicwall": {"family": "software", "fields": {}},
    "spring": {"family": "software", "fields": {}},
    "sqlite": {"family": "software", "fields": {}},
    "srcincite": {"family": "exploit", "fields": {}},
    "suse": {"family": "unix", "fields": {}},
    "susecve": {"family": "unix", "fields": {}},
    "symantec": {"family": "software", "fields": {}},
    "symfony": {"family": "software", "fields": {}},
    "talos": {"family": "info", "fields": {}},
    "talosblog": {"family": "blog", "fields": {}},
    "taosecurity": {"family": "blog", "fields": {}},
    "tenable": {"family": "info", "fields": {}},
    "thehackerblog": {"family": "blog", "fields": {}},
    "thn": {"family": "info", "fields": {}},
    "threatpost": {"family": "info", "fields": {}},
    "tibco": {"family": "software", "fields": {}},
    "tomcat": {"family": "software", "fields": {}},
    "trellix": {"family": "info", "fields": {}},
    "trendmicroblog": {"family": "blog", "fields": {}},
    "typo3": {"family": "software", "fields": {}},
    "ubuntu": {"family": "unix", "fields": {}},
    "ubuntucve": {"family": "unix", "fields": {}},
    "vaadin": {"family": "software", "fields": {"vendorCvss": "any"}},
    "veeam": {"family": "software", "fields": {}},
    "veracode": {"family": "software", "fields": {}},
    "virtuozzo": {"family": "unix", "fields": {}},
    "vivaldi": {"family": "software", "fields": {}},
    "vmware": {"family": "software", "fields": {"vendorCvss": "any"}},
    "vulncheck_kev": {"family": "info", "fields": {"_product": "str", "_vendor": "str", "_vulncheck_reported_exploitation": "list", "_vulncheck_xdb": "any", "cpeConfigurations": "any", "cvssScore": "float", "source": "str"}},
    "vulnerlab": {"family": "exploit", "fields": {"category": "str", "price": "any"}},
    "vulnersosv": {"family": "library", "fields": {"baseAffectedLibrary": "any", "snapshot_date": "str", "transitiveAffectedLibraries": "any"}},
    "vulnrichment": {"family": "cve", "fields": {"assigned": "str", "impacts": "any", "origin": "str", "provider": "str"}},
    "w3af": {"family": "scanner", "fields": {"w3af": "any"}},
    "wallarmlab": {"family": "blog", "fields": {}},
    "websecuritylog": {"family": "blog", "fields": {}},
    "wired": {"family": "blog", "fields": {}},
    "wizblog": {"family": "info", "fields": {}},
    "wolfi": {"family": "unix", "fields": {}},
    "wordfence": {"family": "info", "fields": {}},
    "wpexploit": {"family": "exploit", "fields": {"generation": "int"}},
    "wpvulndb": {"family": "software", "fields": {"exploit": "str", "generation": "int"}},
    "xen": {"family": "software", "fields": {}},
    "xssed": {"family": "bugbounty", "fields": {}},
    "yubico": {"family": "software", "fields": {}},
    "zdi": {"family": "info", "fields": {}},
    "zdt": {"family": "exploit", "fields": {"category": "str"}},
    "zeroscience": {"family": "exploit", "fields": {}},
}
