"""Canonical human-readable descriptions for every field the Vulners API emits.

Single source of truth shared by the hand-written models (:mod:`.bulletin`), the
factory-built per-collection models (:mod:`.collections`) and the documentation.
Kept in sync with live data by ``dev-tools/data-models/sample_collections.py``,
which lists any field seen live that has no description here (and the test suite
enforces full coverage offline).

Authored descriptions (not machine-generated): each explains what the field means
and why it is there, for both the docs and IDE tooltips.
"""

from __future__ import annotations

FIELD_DESCRIPTIONS: dict[str, str] = {
    # --- identity / core ---
    "id": "Unique document identifier (e.g. a CVE id, exploit id or advisory id).",
    "type": "Source collection the document comes from (cve, exploitdb, ubuntu, …).",
    "bulletinFamily": "Broad family the document belongs to (cve, exploit, software, …).",
    "title": "Human-readable title of the document.",
    "description": "Full text or summary of the vulnerability/advisory.",
    "href": "Canonical URL of the document at its original source.",
    "vhref": "URL of the document on vulners.com.",
    "sourceHref": "URL of the raw source object, when it differs from href.",
    "sourceData": "Raw, unparsed source body as delivered by the origin.",
    "sourceAvailable": "Whether the raw source data is available for this document.",
    "vendorId": "Vendor's own identifier for the advisory, when provided.",
    "provider": "Organization that produced the record (e.g. the CNA).",
    "origin": "Ingestion origin/pipeline the record came through.",
    "reporter": "Person or organization credited with reporting/authoring it.",
    "assigned": "Assignment date/owner recorded by the source (e.g. CVE assignment).",
    "viewCount": "How many times the document has been viewed on Vulners.",
    # --- dates ---
    "published": "Original publication timestamp (ISO-8601).",
    "modified": "Last modification timestamp at the source (ISO-8601).",
    "lastseen": "Last time Vulners observed/refreshed the document (ISO-8601).",
    "dateUpdated": "Source-reported last-update date.",
    "dueDate": "Remediation due date (e.g. CISA KEV required-action deadline).",
    "last_activity": "Timestamp of the most recent activity on the item.",
    "snapshot_date": "Date of the data snapshot this record was taken from.",
    "patchPublicationDate": "Date the fixing patch was published.",
    "vulnerabilityPublicationDate": "Date the vulnerability itself was first published.",
    "timestamps": "Vulners lifecycle timestamps (created/updated/enriched/reviewed/…).",
    # --- scoring ---
    "cvss": "Primary CVSS score block (version, base score, vector, severity, source).",
    "cvss2": "CVSS v2 score block.",
    "cvss3": "CVSS v3.x score block.",
    "cvss4": "CVSS v4.0 score block.",
    "cvssScore": "Flat numeric CVSS base score, when only a scalar is provided.",
    "cvssScoreSource": "Which party/standard the CVSS score was taken from.",
    "vendorCVSS": "Vendor-assigned CVSS, as a raw string.",
    "vendorCvss": "Vendor-assigned CVSS score block.",
    "vendorCvss2": "Vendor-assigned CVSS v2.",
    "vendorCvss3": "Vendor-assigned CVSS v3.",
    "vendor_cvss": "Vendor-assigned CVSS (raw object).",
    "vendor_cvss2": "Vendor-assigned CVSS v2 (score/vector).",
    "vendor_cvss3": "Vendor-assigned CVSS v3 (score/vector).",
    "vendor_severity": "Vendor's own qualitative severity rating.",
    "severity": "Qualitative severity band (LOW/MEDIUM/HIGH/CRITICAL).",
    "nessusSeverity": "Severity as rated by the Nessus scanner.",
    "msseverity": "Microsoft's severity rating for the advisory.",
    "msimpact": "Microsoft's impact classification.",
    "vpr": "Tenable Vulnerability Priority Rating block.",
    "epss": "EPSS exploitation-probability forecast datapoints (score + percentile).",
    "metrics": "Raw scoring metrics blob (CNA/ADP/NVD/vendor sub-objects).",
    "enchantments": "Vulners-computed enrichment layer (AI score, tags, related docs).",
    # --- classification / weakness ---
    "cwe": "Associated CWE weakness identifiers.",
    "cweIds": "Associated CWE weakness identifiers (alternate key).",
    "cweList": "Associated CWE weakness identifiers (alternate key).",
    "cwe_id": "Single associated CWE identifier.",
    "problemTypes": "Structured problem-type/weakness records (CVE JSON 5.x).",
    "classification": "Source-specific classification/category of the issue.",
    "category": "Category assigned by the source.",
    "tag": "A single classification tag.",
    "tags": "Classification tags applied to the document.",
    "owasp": "Related OWASP category.",
    # --- linkage / references ---
    "cvelist": "Related CVE identifiers referenced by this document.",
    "references": "External reference URLs.",
    "references_categories": "References grouped by category (canonical/misc).",
    "extraReferences": "Additional reference URLs beyond the primary set.",
    "source_references": "References with their originating source.",
    "related": "Ids of related Vulners documents.",
    "relatesTo": "Identifier this document relates to.",
    "toolHref": "Link to the associated tool/exploit.",
    "repository": "Source code repository associated with the report.",
    "patch_commit_sha": "Commit SHA of the fixing patch.",
    "bugs": "Linked bug-tracker entries.",
    # --- affected products / configuration ---
    "cpe": "Affected products as CPE 2.2 URIs.",
    "cpe23": "Affected products as CPE 2.3 formatted strings.",
    "cpeConfiguration": "Single CPE applicability configuration.",
    "cpeConfigurations": "CPE applicability configurations (NVD-style match tree).",
    "cnaCpeApplicability": "CPE applicability as supplied by the CNA.",
    "affectedConfiguration": "Affected configuration entries.",
    "affectedSoftware": "Affected software products (name/version/operator).",
    "affectedProducts": "Affected product names.",
    "affectedPackage": "Affected OS/distribution packages (name, version, OS, arch).",
    "affectedLibraries": "Affected libraries/packages (name, purl, version range).",
    "baseAffectedLibrary": "The primary affected library (name, purl, version range).",
    "transitiveAffectedLibraries": "Libraries affected transitively via dependencies.",
    "affectedVersions": "Affected version ranges.",
    "vulnerable_products": "Product identifiers known to be vulnerable.",
    "purls": "Affected packages as Package-URL (purl) strings.",
    "cnaAffected": "Affected products as reported by the CNA (CVE JSON 5.x).",
    "adpAffected": "Affected products as reported by an ADP (Authorized Data Publisher).",
    "sourceAffectedData": "Affected-product data in the source's own shape.",
    "aixFileset": "Affected AIX filesets (fileset, product, version).",
    "curlAffects": "Affected curl versions (curl advisories).",
    "curlSeverity": "curl project's severity rating.",
    "hashicorpProducts": "Affected HashiCorp products.",
    "hashicorpBulletinId": "HashiCorp advisory identifier.",
    "jenkinsPlugins": "Affected Jenkins plugins (name, fixed/previous versions).",
    "jenkinsCore": "Affected Jenkins core version.",
    "jenkinsAdvisoryId": "Jenkins advisory identifier.",
    "jenkinsKind": "Jenkins advisory kind (core/plugin).",
    "jenkinsReporter": "Reporter credited by the Jenkins advisory.",
    "kubernetesIssueNumber": "Kubernetes issue number for the advisory.",
    "kubernetesStatus": "Status of the Kubernetes advisory.",
    "product": "Affected product name.",
    "vendor": "Affected product's vendor.",
    "_product": "Affected product name (source-internal key).",
    "_vendor": "Affected product's vendor (source-internal key).",
    # --- remediation ---
    "solution": "Recommended remediation/fix, as text.",
    "solutions": "Structured remediation entries (CVE JSON 5.x).",
    "workarounds": "Structured workaround entries when no fix is available.",
    "mitigations": "Mitigation measures for the issue.",
    "fixes": "Fix references (fixed versions / patches).",
    "requiredAction": "Required remediation action (e.g. CISA KEV directive).",
    "upstreamFix": "Whether/where an upstream fix is available.",
    "withdrawn": "Withdrawal date if the advisory was retracted.",
    "unofficial_repo": "Whether the fix comes from an unofficial repository.",
    # --- exploit / exploitation ---
    "exploit": "Exploit availability/details (source-specific).",
    "exploits": "Related exploit records.",
    "exploitType": "Type of exploit (remote, local, webapps, …).",
    "exploit_type": "Type of exploit (alternate key).",
    "exploitAvailable": "Whether a public exploit is available.",
    "exploitEase": "How easy exploitation is (scanner assessment).",
    "exploitableWith": "Tools/frameworks the issue is exploitable with.",
    "exploitability": "Exploitability assessment block.",
    "exploitProbabilityScoring": "Model-based exploit-probability scoring.",
    "has_poc": "Whether a proof-of-concept is available.",
    "verified": "Whether the exploit/finding was verified.",
    "isExploited": "Whether the vulnerability is known to be exploited.",
    "wildExploited": "Whether the vulnerability is exploited in the wild.",
    "wildExploitedCategory": "Category of in-the-wild exploitation.",
    "wildExploitedReports": "Reports evidencing in-the-wild exploitation.",
    "knownRansomwareCampaignUse": "Ransomware-campaign-use marker, as a string "
    "('Known'/'Unknown', per CISA KEV) — not a boolean.",
    "impact": "Impact description/classification.",
    "impacts": "Structured impact records (CVE JSON 5.x).",
    "denialOfService": "Denial-of-service impact marker, as a string "
    "(e.g. 'N/A') — not a boolean.",
    "metasploitHistory": "Metasploit module history.",
    "metasploitReliability": "Reliability rating of the Metasploit module.",
    "osvdbidlist": "Legacy OSVDB identifiers.",
    "price": "Exploit price (for commercial exploit feeds).",
    "generation": "Internal generation/version counter of the record.",
    "sandboxInfo": "Sandbox detonation information.",
    "threatData": "Aggregated threat-intelligence signals.",
    "threats": "Threat-intelligence entries.",
    "ciscoThreat": "Cisco Talos threat details (files, hashes, subject).",
    "attackerkb": "AttackerKB assessment (attacker value, exploitability).",
    "_vulncheck_reported_exploitation": "VulnCheck-reported exploitation evidence.",
    "_vulncheck_xdb": "VulnCheck exploit/DB cross-references.",
    # --- CVE workflow / status ---
    "vulnStatus": "NVD analysis status of the CVE (Analyzed, Awaiting Analysis, …).",
    "status": "Workflow status of the record.",
    "revision": "Revision number of the advisory.",
    "msDetailRevision": "Microsoft advisory detail revision.",
    "aiDescription": "AI-generated summary of the vulnerability.",
    "webApplicability": "Web-application applicability assessment.",
    # --- Microsoft-specific ---
    "kb": "Microsoft Knowledge Base article id.",
    "kbList": "Microsoft KB article ids covered by the update.",
    "mscve": "Microsoft's CVE identifier for the advisory.",
    "msrc": "Microsoft Security Response Center identifier.",
    "msfamily": "Microsoft product family.",
    "msplatform": "Affected Microsoft platform.",
    "msproducts": "Affected Microsoft products.",
    "msAffectedSoftware": "Affected Microsoft software entries.",
    "superseeds": "Updates this update supersedes.",
    "supersededUpdates": "Updates superseded by this one.",
    "parentseeds": "Updates that supersede this update.",
    "bundledUpdates": "Updates bundled into this one.",
    "prerequisitesUpdates": "Prerequisite updates required before this one.",
    "customerActionRequired": "Whether customer action is required.",
    "faq": "Advisory FAQ entries.",
    "issuingCna": "The CNA that issued the advisory.",
    "supportAreaPaths": "Microsoft support taxonomy paths.",
    "supportAreaPathNodes": "Microsoft support taxonomy nodes.",
    "primarySupportAreaPath": "Primary Microsoft support taxonomy path.",
    # --- scanner-specific ---
    "pluginID": "Scanner plugin identifier (e.g. Nessus plugin id).",
    "naslFamily": "Nessus NASL plugin family.",
    "nmap": "Nmap script details (category, script type).",
    # --- bug bounty ---
    "bounty": "Bounty amount/details paid for the report.",
    "bountyState": "State of the bounty (awarded, pending, …).",
    "h1reporter": "HackerOne reporter profile.",
    "h1team": "HackerOne team/program the report belongs to.",
    "openbugbounty": "Open Bug Bounty metadata (mirror, patch status).",
    "language": "Language of the report.",
    # --- library ecosystem (OSV/Snyk) ---
    "osvAffected": "OSV 'affected' ranges.",
    "osvPackages": "OSV package records (ecosystem, name, purl).",
    "osvSeverity": "OSV severity entries (score, type).",
    "osvCrossReferences": "OSV cross-references to other advisories.",
    "snykData": "Snyk-specific data (exploit maturity, malicious flag).",
    # --- enrichment / provenance details ---
    "attachments": "Binary/media attachments associated with the document.",
    "immutableFields": "Fields the source marks as immutable.",
    "items": "Sub-items/entries contained in the document.",
    "notes": "Free-text notes.",
    "source": "Source name/identifier for the record.",
    "protected_by": "Products/controls that protect against the issue.",
    "mitre_vector": "MITRE ATT&CK vector mapping.",
    # --- vendor scanner/tool provenance flags ---
    "appercut": "AppercutScanner tool provenance (report pages).",
    "exploitpack": "ExploitPack tool provenance (platform, type).",
    "hackapp": "HackApp mobile-app scan provenance.",
    "w3af": "w3af scanner provenance (plugin type).",
    "ossfuzz": "OSS-Fuzz crash details (crash type, project, issue).",
}
